require "fileutils"
require "json"

module RustProjection
  # Generates one domain's worth of types/Fielded impls/commands into
  # `mod_dir`, plus a `metadata.rs` carrying that domain's own canonical IR
  # as an embedded JSON constant — SELF-DESCRIPTION: an app holding the
  # compiled binary can list its own commands, read `given` text, etc. at
  # runtime without a second, hand-maintained description and without going
  # back to Ruby. Nothing generated above reads `metadata.rs` — it exists
  # purely for introspection, the same way a doc comment does, just at
  # runtime instead of read-time.
  module DomainGenerator
    module_function

    def call(ir, source_label, mod_dir, mod_name)
      FileUtils.mkdir_p(mod_dir)
      domain_name = ir[:name]
      generated_aggregates = []

      ir[:aggregates].each do |aggregate|
        value_objects_by_name = aggregate[:value_objects].to_h { |vo| [vo[:name], vo] }

        unsupported = Projector.unsupported_attribute_types(aggregate, value_objects_by_name)
        if unsupported.any?
          puts "skipping #{domain_name}::#{aggregate[:name]}: attribute type(s) #{unsupported.join(', ')} not generated yet " \
               "(a bare, non-list entity-typed attribute isn't resolved to a Rust type)"
          next
        end

        generated_aggregates << aggregate

        path = File.join(mod_dir, "#{aggregate[:name].downcase}.rs")
        File.open(path, "w") do |f|
          f.puts "// GENERATED by bin/project_rust from #{source_label}'s canonical IR."
          f.puts "// Do not hand-edit — re-run bin/project_rust instead."
          f.puts "#![allow(dead_code, unused_variables)]"
          f.puts 'use crate::kernel::Expr;'
          f.puts
          aggregate[:value_objects].each do |vo|
            f.puts Projector.emit_value_object(vo, value_objects_by_name)
            f.puts
          end
          aggregate[:entities].each do |entity|
            f.puts Projector.emit_entity(entity, value_objects_by_name)
            f.puts
          end
          f.puts Projector.emit_record(aggregate, value_objects_by_name)
          f.puts

          aggregate[:commands].each do |command|
            reason = Projector.command_skip_reason(command, aggregate, value_objects_by_name)
            if reason
              puts "skipping #{domain_name}::#{aggregate[:name]}.#{command[:name]}: #{reason}"
              next
            end

            f.puts Projector.emit_command(command, aggregate, domain_name, value_objects_by_name)
            f.puts
          end
        end
        puts "wrote #{path}"
      end

      metadata_path = File.join(mod_dir, "metadata.rs")
      File.open(metadata_path, "w") do |f|
        f.puts "// GENERATED by bin/project_rust — #{source_label}'s own canonical IR,"
        f.puts "// embedded for runtime self-description. Not read by any dispatch"
        f.puts "// function in this module — introspection only."
        f.puts "pub const IR_JSON: &str = #{JSON.pretty_generate(ir).inspect};"
      end
      puts "wrote #{metadata_path}"

      mod_path = File.join(mod_dir, "mod.rs")
      File.open(mod_path, "w") do |f|
        f.puts "// GENERATED by bin/project_rust — re-run it to refresh this list."
        f.puts "pub mod metadata;"
        generated_aggregates.each { |a| f.puts "pub mod #{a[:name].downcase};" }
      end
      puts "wrote #{mod_path}"
    end
  end
end
