module RustProjection
  module Projector
    module_function

    # ── THE JSON COMMAND ROUTER — `dispatch_by_name`'s own per-domain
    # table, generated once (domain_generator.rb calls this last, after
    # every aggregate's own file is written). One `Store` field per
    # generated aggregate — an `InMemoryRepository<T>`, the only
    # `Repository` impl this kernel ships (kernel/repository.rs) — and one
    # match arm per generated command (`command_skip_reason`'s survivors
    # only; a skipped command was never given a `dispatch_*` function to
    # route to either). `kernel/cli.rs` is the one caller: it knows verbs
    # and JSON, nothing domain-specific: this table is the whole bridge.
    #
    # `aggregates` is `[{name:, mod:, record:, commands: [{verb:, fn:,
    # args_struct:, creates:}]}]` — accumulated by domain_generator.rb while
    # it walks the real IR, not re-derived here.
    def emit_registry(domain_name, aggregates)
      store_fields = aggregates.map { |a| "    pub #{a[:mod]}: crate::kernel::InMemoryRepository<super::#{a[:mod]}::#{a[:record]}>," }
      store_inits  = aggregates.map { |a| "            #{a[:mod]}: crate::kernel::InMemoryRepository::new()," }

      dump_arms = aggregates.map do |a|
        prefix = "#{domain_name}::#{a[:name]}#"
        <<~RUST.rstrip
                  for (id, record) in self.#{a[:mod]}.entries() {
                      instances.push((format!("{}{}", #{prefix.inspect}, id), record.to_json()));
                  }
        RUST
      end

      dispatch_arms = aggregates.flat_map do |a|
        a[:commands].map do |c|
          dispatch_call = "super::#{a[:mod]}::dispatch_#{c[:fn]}(&mut store.#{a[:mod]}, #{c[:creates] ? '' : '&id, '}args)"
          id_line = c[:creates] ? "" : "let id = super::#{a[:mod]}::#{a[:record]}::extract_id(args_json)?;\n                    "

          <<~RUST.rstrip
                    #{c[:verb].inspect} => {
                        #{id_line}let args = super::#{a[:mod]}::#{c[:args_struct]}::from_json(args_json)?;
                        #{dispatch_call}.map(|(_, events)| events)
                    }
          RUST
        end
      end

      <<~RUST
        // GENERATED by bin/project_rust — the JSON command router
        // `kernel::cli` dispatches every step through. Do not hand-edit —
        // re-run bin/project_rust instead.
        #![allow(dead_code, unused_variables)]

        pub struct Store {
        #{store_fields.join("\n")}
        }

        impl Store {
            pub fn new() -> Self {
                Self {
        #{store_inits.join("\n")}
                }
            }

            /// Every aggregate this domain declared, dumped as
            /// "Domain::Aggregate#id" -> its own to_json() — the exact key
            /// shape bin/rust_conformance's own comparable["instances"]
            /// builds from Ruby (Fuzzing::Replay.call's own instance key
            /// format, read directly).
            pub fn instances(&self) -> Vec<(String, crate::kernel::Json)> {
                let mut instances = Vec::new();
        #{dump_arms.join("\n")}
                instances
            }
        }

        pub fn dispatch_by_name(
            store: &mut Store,
            verb: &str,
            args_json: &crate::kernel::Json,
        ) -> Result<Vec<crate::kernel::Event>, crate::kernel::Refusal> {
            match verb {
        #{dispatch_arms.join("\n")}
                other => Err(crate::kernel::Refusal::TypeMismatch(format!("unknown command {other:?}"))),
            }
        }
      RUST
    end
  end
end
