// GENERATED by bin/project_reaction_shape from Hecksagain::PrimalIR::
// Shape (lib/hecksagain/primal_ir/shape.rb). Do not hand-edit —
// re-run bin/project_reaction_shape instead. STRUCTURE ONLY here — no
// wiring into orchestrate.rs, see Shape's own header for why.
// Interpretation logic (`resolve_dispatch_bindings`) stays hand-
// written in logic.rs, re-exported below — the same "generate
// structure, handwrite meaning" split kernel/binding/mod.rs already
// draws. `ExecutableBinding` reuses Slice 2's own generated type
// (kernel/binding/mod.rs); `Expr` reuses Slice 1's (kernel/expr/
// mod.rs) — the whole payoff of doing Expression and Binding first
// (ADR 0030's own proof-sequence ordering).

use crate::kernel::binding::ExecutableBinding;

// `Dispatch::VERBATIM`'s Rust counterpart — a real third case, not
// reducible to an empty `Vec<ExecutableBinding>` (see Shape's own
// comment). A TUPLE variant, unlike every other enum below —
// `enum_def`/`enum_variant` (this script's own helpers) only build
// NAMED-field variants, the shape `Context`/`Persistence`/`Failure`
// all actually need; this one 2-variant enum is hand-spelled rather
// than forcing a tuple case through helpers built for a different
// shape.
#[derive(Debug, Clone)]
pub enum Bindings {
    Explicit(Vec<ExecutableBinding>),
    Verbatim,
}

#[derive(Debug, Clone)]
pub struct Trigger {
    pub name: String,
    pub qualifier: Option<String>,
}

#[derive(Debug, Clone)]
pub struct CommandRef {
    pub domain: Option<String>,
    pub command_name: String,
}

#[derive(Debug, Clone)]
pub struct Dispatch {
    pub command_ref: CommandRef,
    pub bindings: Bindings,
}

#[derive(Debug, Clone)]
pub enum Context {
    Stateless,
    Correlated { correlation_key: String, memory: bool },
}

#[derive(Debug, Clone)]
pub enum Persistence {
    Ephemeral,
    Checkpointed { boundary: String, to_state: String },
}

#[derive(Debug, Clone)]
pub enum Failure {
    Drop,
    Managed { retry: u32, compensation: Option<Box<Reaction>> },
}

#[derive(Debug, Clone)]
pub struct Reaction {
    pub trigger: Trigger,
    pub condition: Option<crate::kernel::expr::Expr>,
    pub dispatches: Vec<Dispatch>,
    pub context: Context,
    pub persistence: Persistence,
    pub failure: Failure,
}

mod logic;
pub use logic::resolve_dispatch_bindings;
