# Hecks::Specification
#
# Base mixin that generated specification classes include. Specifications are
# reusable, composable predicate objects that encapsulate business rules.
# Supports boolean composition via and/or/not operators.
#
# Part of the domain behavior layer. Generated by SpecificationGenerator and
# included in specification classes within the domain gem.
#
#   class HighRisk
#     include Hecks::Specification
#
#     def satisfied_by?(loan)
#       loan.principal > 50_000 && loan.rate > 10
#     end
#   end
#
#   spec = HighRisk.new
#   spec.satisfied_by?(loan)           # => true/false
#   combo = spec.and(AnotherSpec.new)   # => AndSpecification
#   combo.satisfied_by?(loan)           # => true/false
#
module Hecks
  module Specification
    def self.included(base)
      base.extend(ClassMethods)
    end

    module ClassMethods
      def satisfied_by?(object)
        new.satisfied_by?(object)
      end
    end

    def satisfied_by?(_object)
      raise NotImplementedError, "#{self.class}#satisfied_by? must be implemented"
    end

    def and(other)
      AndSpecification.new(self, other)
    end

    def or(other)
      OrSpecification.new(self, other)
    end

    def not
      NotSpecification.new(self)
    end

    # Composite: both specifications must be satisfied
    class AndSpecification
      include Specification

      def initialize(left, right)
        @left = left
        @right = right
      end

      def satisfied_by?(object)
        @left.satisfied_by?(object) && @right.satisfied_by?(object)
      end
    end

    # Composite: at least one specification must be satisfied
    class OrSpecification
      include Specification

      def initialize(left, right)
        @left = left
        @right = right
      end

      def satisfied_by?(object)
        @left.satisfied_by?(object) || @right.satisfied_by?(object)
      end
    end

    # Composite: the wrapped specification must NOT be satisfied
    class NotSpecification
      include Specification

      def initialize(spec)
        @spec = spec
      end

      def satisfied_by?(object)
        !@spec.satisfied_by?(object)
      end
    end
  end
end
