# Hecks::Utils
#
# Shared utility functions used across the framework. Provides constant
# sanitization, underscore conversion, type labeling, keyword detection,
# block source extraction, and object serialization.
# Infrastructure layer — consumed by generators, DSL, services, and CLI.
#
#   Hecks::Utils.sanitize_constant("My Pizza")  # => "MyPizza"
#   Hecks::Utils.underscore("PizzaDomain")       # => "pizza_domain"
#
module Hecks
  module Utils
    # Ruby reserved keywords that cannot be used as bare keyword parameters
    # in method signatures (e.g. `def initialize(class:)` is invalid syntax).
    RUBY_KEYWORDS = %w[
      __FILE__ __LINE__ __ENCODING__
      BEGIN END
      alias and begin break case class def defined? do else elsif end
      ensure false for if in module next nil not or redo rescue retry
      return self super then true undef unless until when while yield
    ].freeze

    # Attributes that are auto-generated by aggregate classes and should
    # not be duplicated in attr_reader or constructor params.
    RESERVED_AGGREGATE_ATTRS = %w[id].freeze

    module_function

    # Sanitize a string into a valid Ruby constant name (PascalCase).
    # Removes special characters, handles leading digits, capitalizes segments.
    #
    #   sanitize_constant("pizza")     # => "Pizza"
    #   sanitize_constant("My Pizza")  # => "MyPizza"
    #   sanitize_constant("My-Pizza")  # => "MyPizza"
    #   sanitize_constant("3DModel")   # => "Model3D"  (leading digit moved)
    #   sanitize_constant("My.App")    # => "MyApp"
    #   sanitize_constant("My!App?")   # => "MyApp"
    #   sanitize_constant("")          # => "Unnamed"
    #
    def sanitize_constant(name)
      # Remove characters not valid in Ruby identifiers (keep letters, digits, underscores, spaces, hyphens as separators)
      cleaned = name.to_s.gsub(/[^a-zA-Z0-9_\s-]/, "")

      # Split on word boundaries (spaces, hyphens, underscores) and capitalize each segment
      parts = cleaned.split(/[\s\-_]+/).reject(&:empty?)

      return "Unnamed" if parts.empty?

      # Capitalize each segment for PascalCase
      result = parts.map { |p| p[0].upcase + p[1..].to_s }.join

      # If the result starts with a digit, move leading digits to the end
      if result.match?(/\A\d/)
        leading_digits = result[/\A\d+/]
        rest = result.sub(/\A\d+/, "")
        if rest.empty?
          result = "N#{leading_digits}"
        else
          result = rest[0].upcase + rest[1..].to_s + leading_digits
        end
      end

      result
    end

    # Check if an attribute name is a Ruby keyword that can't be used
    # as a bare keyword parameter in def initialize(name:).
    def ruby_keyword?(name)
      RUBY_KEYWORDS.include?(name.to_s)
    end

    def underscore(str)
      str.gsub(/([A-Z]+)([A-Z][a-z])/, '\1_\2')
         .gsub(/([a-z\d])([A-Z])/, '\1_\2')
         .downcase
    end

    def type_label(attr)
      if attr.list?
        "list_of(#{attr.type})"
      elsif attr.reference?
        "reference_to(#{attr.type})"
      else
        attr.type.to_s
      end
    end

    def block_source(block)
      return "true" unless block
      file, start_line = block.source_location
      lines = File.readlines(file)

      # Single-line block: `query "Foo" do where(x: 1) end`
      first = lines[start_line - 1].strip
      if first.match?(/\bdo\b.*\bend\s*$/)
        return first.sub(/^.*?\bdo\s*(\|[^|]*\|\s*)?/, "").sub(/\s*end\s*$/, "").strip
      end

      # Multi-line block: collect body lines between do and end
      body_lines = []
      depth = 0
      lines[start_line..-1].each do |l|
        stripped = l.strip
        break if depth == 0 && stripped == "end"
        body_lines << stripped
        depth += 1 if stripped.match?(/\b(do|def|class|module|if|unless|case|begin)\b/)
        depth -= 1 if stripped == "end"
      end
      body_lines.reject(&:empty?).join("\n")
    rescue StandardError
      "true"
    end

    # Returns attribute names for an object, using hecks_attributes metadata
    # if available, otherwise falling back to initialize parameter introspection.
    def object_attr_names(obj)
      klass = obj.is_a?(Class) ? obj : obj.class
      names = [:id]
      if klass.respond_to?(:hecks_attributes)
        names += klass.hecks_attributes.map { |a| a[:name] }
      else
        klass.instance_method(:initialize).parameters.each do |_, name|
          names << name if name && name != :id
        end
      end
      names += [:created_at, :updated_at] if obj.respond_to?(:created_at)
      names
    end

    # Serializes an object to a hash using attribute metadata.
    def serialize_object(obj)
      object_attr_names(obj).each_with_object({}) do |name, h|
        h[name.to_s] = obj.send(name) if obj.respond_to?(name)
      end
    end
  end
end
