require_relative "../projector"

module Hecks
  module Projections
    # A DOMAIN'S OWN SHAPE, PROJECTED AS MERMAID DIAGRAMS — the same
    # trick `Projections::Reference`/`DocsProjector` already play for
    # prose, one level further: a diagram generated FROM the
    # declaration can't drift from it the way a hand-drawn one
    # inevitably does, because there is no second copy to forget to
    # update.
    #
    # MERMAID, NOT GRAPHVIZ (the two considered) — every diagram type
    # below has a Mermaid form purpose-built for exactly what the
    # underlying construct already is (a `lifecycle` IS a state
    # machine, `has_many`/`belongs_to` already speaks in cardinality,
    # `emits`/`trigger` already IS a directed graph), and the output is
    # plain text that renders natively wherever this project's own docs
    # already live — GitHub markdown, this repo's generated docs, Claude
    # Artifacts — with no build step and no external binary. Graphviz's
    # DOT format needs an actual render step (a `dot` binary, or a WASM
    # port) to become anything viewable, which is a real dependency this
    # repository's own discipline (see rust/parser's Cargo.toml: "no
    # dependency earns its way past std") would rather not take just to
    # draw a diagram.
    #
    # THREE DIAGRAM KINDS, one file each per domain except lifecycles
    # (one per lifecycle-bearing construct, since that's how a reader
    # actually reaches for it — looking at ONE aggregate's states, not
    # every aggregate's at once):
    #
    #   <Name>_lifecycle.mmd  stateDiagram-v2  one per lifecycle
    #   relationships.mmd     erDiagram        the whole domain's has_many/
    #                                          has_one/belongs_to/reference_to
    #   dispatch.mmd          flowchart        the whole domain's command
    #                                          emits -> policy trigger chains
    #
    # NAMES ARE USED BARE, UNSANITIZED, as Mermaid node/entity ids — safe
    # because this language's own word grammar only ever admits simple
    # CamelCase/snake_case identifiers here (confirmed: no space or
    # punctuation appears in any real aggregate/command/event name across
    # the corpus this projects from), not because arbitrary text would be.
    module Diagrams
      extend Hecks::Projector::Target

      projects_as :diagrams, emits: :files

      module_function

      def call(bluebook:, options: {})
        files = {}

        holders_with_lifecycle(bluebook).each do |holder|
          files["#{holder.hecks_name}_lifecycle.mmd"] = lifecycle_diagram(bluebook, holder)
        end

        if (diagram = relationship_diagram(bluebook))
          files["relationships.mmd"] = diagram
        end

        if (diagram = dispatch_diagram(bluebook))
          files["dispatch.mmd"] = diagram
        end

        files
      end

      # ── shared ────────────────────────────────────────────────────────

      # AN ENTITY CAN CARRY ITS OWN LIFECYCLE, RELATIONSHIP, OR COMMAND
      # TOO — its own `lifecycle`/`reference_to`/`command` block,
      # addressed through its holding aggregate the same way
      # `DocsProjector` already treats an aggregate and its entities
      # alike. Walking both here means a domain's entity gaining any of
      # these needs no change to this file.
      def holders(bluebook)
        bluebook.aggregates.flat_map { |aggregate| [aggregate, *aggregate.entities] }
      end

      def holders_with_lifecycle(bluebook) = holders(bluebook).select(&:lifecycle)

      # `chapter_name` DRIVES THE RE-RUN HINT ALWAYS — that's the one
      # argument `bin/project_diagrams` actually takes, regardless of
      # which single aggregate/entity `subject` happens to name. Passing
      # the wrong one here once already produced a real, committed
      # `Order_lifecycle.mmd` telling a reader to run
      # `bin/project_diagrams <domain-path> Order` — a chapter name
      # Hecks.boot has never heard of.
      def header(chapter_name, subject)
        <<~HEADER
          %% GENERATED by bin/project_diagrams from #{subject} — DO NOT EDIT BY HAND.
          %% Re-run `bin/project_diagrams <domain-path> #{chapter_name}` after any change.
        HEADER
      end

      # ── lifecycle -> stateDiagram-v2 ─────────────────────────────────

      def lifecycle_diagram(bluebook, holder)
        lifecycle = holder.lifecycle
        edges = lifecycle.transitions.flat_map do |command_name, transition|
          Array(transition.from).map { |from_state| "    #{from_state} --> #{transition.target}: #{command_name}" }
        end

        subject = "#{holder.hecks_name}'s own declared lifecycle (field: #{lifecycle.field})"
        <<~MERMAID
          #{header(bluebook.name, subject)}stateDiagram-v2
              [*] --> #{lifecycle.default}
          #{edges.join("\n")}
        MERMAID
      end

      # ── relationships -> erDiagram ───────────────────────────────────

      # STANDARD CROW'S-FOOT READING, the same convention every ORM's own
      # ERD generator (Rails' erd gem included) already uses:
      # `has_many`/`has_one` are read from the OWNING side — one Holder
      # relates to many/one Target. `belongs_to`/`reference_to` are read
      # from the TARGET's side instead — one Target can be pointed at by
      # MANY Holders — because a bare reference carries no promise about
      # how many holders point back at it; "many" is the honest default
      # absent a declared uniqueness rule this language doesn't expose.
      # `optional?` only ever softens the side that can genuinely be
      # absent (a nilable reference, an empty has_one) — never the
      # crow's-foot "many" marker, which is a structural fact independent
      # of any one instance's optionality.
      def relationship_diagram(bluebook)
        edges = holders(bluebook).flat_map do |holder|
          holder.attributes.select(&:reference?).map { |attribute| relationship_edge(holder, attribute) }
        end
        return nil if edges.empty?

        subject = "#{bluebook.name}'s own declared reference_to/belongs_to/has_many/has_one attributes"
        "#{header(bluebook.name, subject)}erDiagram\n#{edges.join("\n")}\n"
      end

      def relationship_edge(holder, attribute)
        target = attribute.type.target_name
        case attribute.relationship
        when "has_many"
          %(    #{holder.hecks_name} ||--o{ #{target} : "#{attribute.name}")
        when "has_one"
          %(    #{holder.hecks_name} ||--#{attribute.optional? ? 'o|' : '||'} #{target} : "#{attribute.name}")
        when "belongs_to", "reference_to"
          %(    #{target} #{attribute.optional? ? '|o' : '||'}--o{ #{holder.hecks_name} : "#{attribute.name}")
        end
      end

      # ── dispatch -> flowchart ─────────────────────────────────────────

      # A COMMAND NODE, STADIUM-SHAPED (`(["..."])`); AN EVENT NODE,
      # HEXAGONAL (`{{"..."}}`) — one visual vocabulary for "a thing
      # someone does" versus "a fact that happened", matching the
      # language's own verb/event distinction. Command ids are qualified
      # by their owning aggregate (`cmd_Order_Purchase`) since two
      # aggregates may share a command name; event ids are bare
      # (`evt_PizzaCreated`) since an event is this domain's own
      # addressing key, the same way `policy.on_event` reaches it.
      def dispatch_diagram(bluebook)
        lines = []

        holders(bluebook).each do |holder|
          holder.commands.each do |command|
            command.emits.each { |event| lines << emits_edge(holder, command, event) }
          end
        end

        bluebook.policies.each { |policy| lines << trigger_edge(policy) }

        lines.compact!
        return nil if lines.empty?

        subject = "#{bluebook.name}'s own declared commands' emits and policies' on/trigger"
        "#{header(bluebook.name, subject)}flowchart LR\n#{lines.uniq.join("\n")}\n"
      end

      def emits_edge(holder, command, event)
        %(    #{command_node(holder.hecks_name, command.hecks_name)} -->|emits| #{event_node(event)})
      end

      # `on_event` IS SOMETIMES AGGREGATE-QUALIFIED
      # (`"Account.AccountFrozen"`) AND SOMETIMES BARE
      # (`"CustomerSuspended"`) in the real corpus — `emits` never is,
      # so this always matches against the bare tail, the same
      # normalization a reader has to do by eye today.
      #
      # A TRIGGER CROSSING INTO ANOTHER DOMAIN (`policy.target_domain`)
      # still draws — the target command just has no incoming `emits`
      # edge of its own here, which honestly shows "dispatch continues
      # elsewhere" rather than silently dropping the edge. The label
      # names which domain, so that's not a dead end on the page either.
      def trigger_edge(policy)
        bare_event = policy.on_event.to_s.split(".").last
        aggregate_name, command_name = policy.trigger_command.to_s.split(".", 2)
        label = policy.target_domain ? "triggers in #{policy.target_domain}" : "triggers"
        %(    #{event_node(bare_event)} -->|#{label}| #{command_node(aggregate_name, command_name)})
      end

      def command_node(aggregate_name, command_name)
        %(cmd_#{aggregate_name}_#{command_name}(["#{aggregate_name}.#{command_name}"]))
      end

      def event_node(event_name) = %(evt_#{event_name}{{"#{event_name}"}})
    end
  end
end
