require_relative "../projector"

module Hecks
  module Projections
    # A DOMAIN'S OWN LIFECYCLES, PROJECTED AS MERMAID STATE DIAGRAMS —
    # the same trick `Projections::Reference`/`DocsProjector` already
    # play for prose, one level further: a diagram generated FROM the
    # declaration can't drift from it the way a hand-drawn one
    # inevitably does, because there is no second copy to forget to
    # update.
    #
    # MERMAID, NOT GRAPHVIZ (the two considered) — `stateDiagram-v2` is
    # purpose-built for exactly what a `lifecycle`/`transition` block
    # already is (states, an initial state, labeled edges), and the
    # output is plain text that renders natively wherever this
    # project's own docs already live — GitHub markdown, this repo's
    # generated docs, Claude Artifacts — with no build step and no
    # external binary. Graphviz's DOT format needs an actual render
    # step (a `dot` binary, or a WASM port) to become anything
    # viewable, which is a real dependency this repository's own
    # discipline (see rust/parser's Cargo.toml: "no dependency earns
    # its way past std") would rather not take just to draw a diagram.
    #
    # MVP SCOPE: lifecycle diagrams only. Relationship diagrams
    # (`erDiagram`, from `has_many`/`has_one`/`belongs_to`/
    # `reference_to`) and dispatch-flow diagrams (`flowchart`, from a
    # command's `emits` reaching a `policy`'s `trigger`) are sketched
    # in the same shape but not built yet — each is its own render_*
    # method away, not a redesign.
    module Diagrams
      extend Hecks::Projector::Target

      projects_as :diagrams, emits: :files

      module_function

      # ONE FILE PER LIFECYCLE, not one file per domain — matches how a
      # real reader reaches for this (looking at ONE aggregate's
      # states), and means a domain gaining a second lifecycle-bearing
      # construct never has to touch this method, only add to what it
      # walks over.
      def call(bluebook:, options: {})
        holders_with_lifecycle(bluebook).to_h do |holder|
          ["#{holder.hecks_name}_lifecycle.mmd", lifecycle_diagram(holder)]
        end
      end

      # AN ENTITY CAN CARRY ITS OWN LIFECYCLE TOO (its own `lifecycle`
      # block, addressed through its holding aggregate —
      # `DocsProjector#lifecycle_section` already treats an aggregate
      # and its entities the same way for this exact reason). Walking
      # both here for free costs nothing today (no entity in the real
      # corpus has one yet) and means the day one does, this needs no
      # change.
      def holders_with_lifecycle(bluebook)
        bluebook.aggregates.flat_map { |aggregate| [aggregate, *aggregate.entities] }
                .select(&:lifecycle)
      end

      def lifecycle_diagram(holder)
        lifecycle = holder.lifecycle
        edges = lifecycle.transitions.flat_map do |command_name, transition|
          Array(transition.from).map { |from_state| "    #{from_state} --> #{transition.target}: #{command_name}" }
        end

        <<~MERMAID
          %% GENERATED by bin/project_diagrams from #{holder.hecks_name}'s own declared
          %% lifecycle (field: #{lifecycle.field}) — DO NOT EDIT BY HAND.
          %% Re-run `bin/project_diagrams <domain-path>` after any lifecycle change.
          stateDiagram-v2
              [*] --> #{lifecycle.default}
          #{edges.join("\n")}
        MERMAID
      end
    end
  end
end
