Gem::Specification.new do |s|
  s.name = "model_registry_domain"; s.version = "0.1.0"
  s.authors = ["Generated by Hecks"]; s.summary = "ModelRegistry domain model"
  s.description = "Pure domain gem generated by Hecks"; s.license = "MIT"
  s.files = Dir["lib/**/*", "docs/**/*", "hecks_domain.rb", "verbs.txt"]; s.require_paths = ["lib"]
  s.required_ruby_version = ">= 3.0"
  s.add_dependency "hecks"
  s.add_development_dependency "rspec", "~> 3.0"
end
