Gem::Specification.new do |s|
  s.name        = "pizzas_domain"
  s.version     = "0.1.0"
  s.authors     = ["Generated by Hecks"]
  s.summary     = "PizzasDomain domain model (standalone)"
  s.files       = Dir["lib/**/*"]
  s.require_paths = ["lib"]
  s.add_dependency "webrick", ">= 1.7"
  s.add_development_dependency "rspec", "~> 3.0"
end
