Gem::Specification.new do |spec|
  spec.name          = "billing_domain"
  spec.version       = "0.1.0"
  spec.authors       = ["Generated by Hecks"]
  spec.summary       = "Billing domain model"
  spec.description   = "Pure domain gem generated by Hecks"
  spec.license       = "MIT"

  spec.files         = Dir["lib/**/*", "docs/**/*", "hecks_domain.rb"]
  spec.require_paths = ["lib"]

  spec.required_ruby_version = ">= 3.0"

  spec.add_development_dependency "rspec", "~> 3.0"
end
