// GENERATED by bin/project_kernel_capabilities from Grammar.admitted_operators's own `category` field.
// Do not hand-edit — re-run bin/project_kernel_capabilities instead.
//
// Ground truth: Hecks::Grammar.admitted_operators (lib/hecks/
// grammar.rb), the SAME live-booted call bin/expression_projection
// uses — grouped by the `category` field Evaluator::PROJECTION already
// partitions comparison operators by (evaluator.rb).

pub mod logical;
pub mod membership;
pub mod comparison;
pub mod arithmetic;
pub mod sign_test;
pub mod sized;
pub mod to_string;

/// One variant per real expression-operator category the Ruby
/// grammar admits, in the order Grammar.admitted_operators's own `category` field declares them. Every match
/// over this enum in the kernel (rust/src/kernel/expr.rs) is written
/// WITHOUT a wildcard `_ =>` arm — see expr.rs's own header for why:
/// a wildcard here would let a newly-admitted capability compile
/// silently into a router that never calls the new file this same
/// regeneration adds a `pub mod` line for above.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OperatorCategory {
    Logical,
    Membership,
    Comparison,
    Arithmetic,
    SignTest,
    Sized,
    ToString,
}

impl OperatorCategory {
    /// The `rust/src/kernel/expression_operators/<name>.rs` file this
    /// variant names — `bin/rust_kernel_coverage`'s own existence
    /// check reads this, so the file-name spelling here is the ONE
    /// place that ever needs to change if a name is renamed.
    pub fn module_name(&self) -> &'static str {
        match self {
            OperatorCategory::Logical => "logical",
            OperatorCategory::Membership => "membership",
            OperatorCategory::Comparison => "comparison",
            OperatorCategory::Arithmetic => "arithmetic",
            OperatorCategory::SignTest => "sign_test",
            OperatorCategory::Sized => "sized",
            OperatorCategory::ToString => "to_string",
        }
    }

    pub const ALL: &'static [OperatorCategory] = &[OperatorCategory::Logical, OperatorCategory::Membership, OperatorCategory::Comparison, OperatorCategory::Arithmetic, OperatorCategory::SignTest, OperatorCategory::Sized, OperatorCategory::ToString];
}
