Gem::Specification.new do |s|
  s.name = "pizzas_domain"; s.version = "2026.03.29.8"
  s.authors = ["Generated by Hecks"]; s.summary = "Pizzas domain model"
  s.description = "Pure domain gem generated by Hecks"; s.license = "MIT"
  s.files = Dir["lib/**/*", "docs/**/*", "hecks_domain.rb", "verbs.txt"]; s.require_paths = ["lib"]
  s.required_ruby_version = ">= 3.0"
  s.add_dependency "hecks"
  s.add_development_dependency "rspec", "~> 3.0"
end
