// GENERATED by bin/project_expr_shape from Hecksagain::Bluebook::
// Expression::NodeShapeRust (lib/hecksagain/bluebook/expression/
// node_shape_rust.rb). Do not hand-edit — re-run bin/project_expr_shape
// instead. Interpretation logic (`interpret`/`category_of`/
// `dispatch_operator`, `Value`, `Field`/`Fielded`, `EvalContext`, etc.)
// stays hand-written in logic.rs, re-exported below — this file is
// structure only, the same split binding/mod.rs already draws.
//
// `Resolve` and `ArrayLiteral` are real Ruby nodes with no variant
// here on purpose — see NodeShapeRust's own header for why.
//
// `Comparison` re-exported here, `pub`, not just `use`d — external
// callers reach it as `crate::kernel::expr::Comparison` (the same
// path it always had, before `expr.rs` became a directory), and the
// `Expr` enum's own `Compare`/`SignTest` fields need it in scope
// either way.

pub use crate::kernel::expression_operators::comparison::Comparison;

#[derive(Debug, Clone)]
#[allow(dead_code)]
pub enum Expr {
    Or(Box<Expr>, Box<Expr>),
    And(Box<Expr>, Box<Expr>),
    Not(Box<Expr>),
    Compare { op: Comparison, left: Box<Expr>, right: Box<Expr> },
    Include { haystack: Box<Expr>, needle: Box<Expr> },
    Int(i64),
    Float(f64),
    Str(String),
    Bool(bool),
    Nil,
    Add(Box<Expr>, Box<Expr>),
    SignTest { op: Comparison, receiver: Box<Expr> },
    Empty(Box<Expr>),
    ToS(Box<Expr>),
    Modulo { receiver: Box<Expr>, divisor: Box<Expr> },
    Size(Box<Expr>),
    Lookup(&'static str),
    MatchesRegex { receiver: Box<Expr>, pattern: String, flags: String },
    Presence { receiver: Box<Expr>, negated: bool },
    Split { receiver: Box<Expr>, separator: String },
    First(Box<Expr>),
    Last(Box<Expr>),
    StartsWith { receiver: Box<Expr>, substring: String },
    EndsWith { receiver: Box<Expr>, substring: String },
}

mod logic;
pub use logic::*;
