// GENERATED by bin/project_binding_shape from Hecksagain::Bluebook::
// Expression::BindingShape (lib/hecksagain/bluebook/expression/
// binding_shape.rb). Do not hand-edit — re-run bin/project_binding_shape
// instead. Interpretation logic (`lower`/`resolve`) stays hand-written
// in logic.rs, re-exported below — this file is structure only, the
// same split bin/project_kernel_capabilities already draws for
// expression_operators/attribute_shapes.

use crate::kernel::expr::Value;

#[derive(Debug, Clone, PartialEq)]
pub enum Source {
    Literal { value: Value },
    Reference { name: String, priority: Vec<String> },
}

#[derive(Debug, Clone, PartialEq)]
pub struct ExecutableBinding {
    pub destination: String,
    pub source: Source,
}

mod logic;
pub use logic::{lower, resolve, SourceBucket, Sources};
