// GENERATED BY bin/ir_rust_registry — DO NOT EDIT BY HAND.
//
// Every domain `bin/ir_rust` has projected into this binary, as one table
// — always all of them, declared here ; WHICH ones actually compile in is
// a Cargo feature (`rust/Cargo.toml`'s own `[features]`, one per domain,
// `default` carrying all six), not a different generated file. `mod.rs`
// reads this generically (`by_source`/`by_name`/`names()`) instead of
// hand-matching each chapter — adding a projected domain means running
// `bin/ir_rust`, then this, then naming its feature in `rust/Cargo.toml`
// and `rust/cli/Cargo.toml`, and touching no hand-written logic at all.
//
// Source: rust/src/bluebook/projected/*.rs (each file's own `CHAPTER` and
// `SOURCE_SHA` constants — bin/ir_rust emits both).
// Regenerate: bin/ir_rust_registry > rust/src/bluebook/projected/registry.rs
//
// Held equal to the generator's current output by
// spec/ir_rust_registry_export_spec.rb.

#[cfg(feature = "banking")]
pub mod banking;
#[cfg(feature = "expression")]
pub mod expression;
#[cfg(feature = "pizzas")]
pub mod pizzas;
#[cfg(feature = "reflex")]
pub mod reflex;
#[cfg(feature = "till_room")]
pub mod till_room;
#[cfg(feature = "wire")]
pub mod wire;

pub struct Projected {
    pub chapter: &'static str,
    pub sha: &'static str,
    pub domain: fn() -> crate::ir::Domain,
}

/// A FUNCTION, NOT A `const` SLICE — `#[cfg]` on one PUSH per domain is
/// stable ; `#[cfg]` on individual elements of a `&[...]` literal is not,
/// on stable Rust (`stmt_expr_attributes`, still nightly-only). Called
/// once per lookup rather than held as a static table — a handful of
/// domains, never on a hot path — is the price of that, and it is a small
/// one.
pub fn registry() -> Vec<Projected> {
    let mut items = Vec::new();
    #[cfg(feature = "banking")]
    items.push(Projected { chapter: "Banking", sha: banking::SOURCE_SHA, domain: banking::domain });
    #[cfg(feature = "expression")]
    items.push(Projected { chapter: "Expression", sha: expression::SOURCE_SHA, domain: expression::domain });
    #[cfg(feature = "pizzas")]
    items.push(Projected { chapter: "Pizzas", sha: pizzas::SOURCE_SHA, domain: pizzas::domain });
    #[cfg(feature = "reflex")]
    items.push(Projected { chapter: "Reflex", sha: reflex::SOURCE_SHA, domain: reflex::domain });
    #[cfg(feature = "till_room")]
    items.push(Projected { chapter: "TillRoom", sha: till_room::SOURCE_SHA, domain: till_room::domain });
    #[cfg(feature = "wire")]
    items.push(Projected { chapter: "Wire", sha: wire::SOURCE_SHA, domain: wire::domain });
    items
}
