# Hecks::Generators::Infrastructure::DomainGemGenerator::FileWriter
#
# Writes generated files to disk — aggregates, value objects, commands,
# events, policies, queries, ports, adapters, gemspec, and entry point.
#
module Hecks
  module Generators
    module Infrastructure
      class DomainGemGenerator
        module FileWriter
          private

          def generate_gemspec(root, gem_name, mod)
            write_file(root, "#{gem_name}.gemspec", <<~RUBY)
              Gem::Specification.new do |s|
                s.name = "#{gem_name}"; s.version = "#{@version}"
                s.authors = ["Generated by Hecks"]; s.summary = "#{@domain.name} domain model"
                s.description = "Pure domain gem generated by Hecks"; s.license = "MIT"
                s.files = Dir["lib/**/*", "docs/**/*", "hecks_domain.rb"]; s.require_paths = ["lib"]
                s.required_ruby_version = ">= 3.0"
                s.add_development_dependency "rspec", "~> 3.0"
              end
            RUBY
          end

          def generate_entry_point(root, gem_name, mod)
            write_file(root, "lib/#{gem_name}.rb", AutoloadGenerator.new(@domain).generate_entry_point)
          end

          def generate_aggregates(root, gem_name, mod)
            @domain.aggregates.each do |agg|
              safe_name = Hecks::Utils.sanitize_constant(agg.name)
              snake = Hecks::Utils.underscore(safe_name)
              base = "lib/#{gem_name}/#{snake}"

              agg_gen = Domain::AggregateGenerator.new(agg, domain_module: mod)
              autoload_gen = AutoloadGenerator.new(@domain)
              autoloads = autoload_gen.generate_aggregate_autoloads(agg, gem_name, mod)

              agg_code = agg_gen.generate
              agg_code = inject_autoloads(agg_code, autoloads, safe_name)
              write_file(root, "#{base}/#{snake}.rb", agg_code)

              agg.value_objects.each do |vo|
                vo_gen = Domain::ValueObjectGenerator.new(vo, domain_module: mod, aggregate_name: safe_name)
                write_file(root, "#{base}/#{Hecks::Utils.underscore(vo.name)}.rb", vo_gen.generate)
              end

              agg.commands.each do |cmd|
                cmd_gen = Domain::CommandGenerator.new(cmd, domain_module: mod, aggregate_name: safe_name)
                write_file(root, "#{base}/commands/#{Hecks::Utils.underscore(cmd.name)}.rb", cmd_gen.generate)
              end

              agg.events.each do |evt|
                evt_gen = Domain::EventGenerator.new(evt, domain_module: mod, aggregate_name: safe_name)
                write_file(root, "#{base}/events/#{Hecks::Utils.underscore(evt.name)}.rb", evt_gen.generate)
              end

              agg.policies.each do |pol|
                pol_gen = Domain::PolicyGenerator.new(pol, domain_module: mod, aggregate_name: safe_name)
                write_file(root, "#{base}/policies/#{Hecks::Utils.underscore(pol.name)}.rb", pol_gen.generate)
              end
            end
          end

          def generate_queries(root, gem_name, mod)
            @domain.aggregates.each do |agg|
              safe = Hecks::Utils.sanitize_constant(agg.name)
              snake = Hecks::Utils.underscore(safe)
              agg.queries.each do |q|
                write_file(root, "lib/#{gem_name}/#{snake}/queries/#{Hecks::Utils.underscore(q.name)}.rb",
                           Domain::QueryGenerator.new(q, domain_module: mod, aggregate_name: safe).generate)
              end
            end
          end

          def generate_ports(root, gem_name, mod)
            @domain.aggregates.each do |agg|
              snake = Hecks::Utils.underscore(Hecks::Utils.sanitize_constant(agg.name))
              write_file(root, "lib/#{gem_name}/ports/#{snake}_repository.rb",
                         Infrastructure::PortGenerator.new(agg, domain_module: mod).generate)
            end
          end

          def generate_adapters(root, gem_name, mod)
            @domain.aggregates.each do |agg|
              snake = Hecks::Utils.underscore(Hecks::Utils.sanitize_constant(agg.name))
              write_file(root, "lib/#{gem_name}/adapters/#{snake}_memory_repository.rb",
                         Infrastructure::MemoryAdapterGenerator.new(agg, domain_module: mod).generate)
            end
          end

          def generate_domain_rb(root)
            write_file(root, "hecks_domain.rb", DslSerializer.new(@domain).serialize)
          end

          def inject_autoloads(code, autoloads, agg_name)
            return code if autoloads.strip.empty?
            marker = "class #{agg_name}\n"
            code.sub(marker, "#{marker}#{autoloads}\n\n")
          end

          def write_file(root, relative_path, content)
            path = File.join(root, relative_path)
            FileUtils.mkdir_p(File.dirname(path))
            File.write(path, content)
          end
        end
      end
    end
  end
end
