// GENERATED BY bin/ir_dispatch_words — DO NOT EDIT BY HAND.
//
// Which word opens which category, per context — projected from the
// language's own declared syntax (Syntax::Keyword, rows where `opens` is not
// empty).
// Source: lib/hecksagain/language/bluebook/syntax.bluebook
// Regenerate: bin/ir_dispatch_words > rust/src/bluebook/ir_dispatch_words.rs
//
// Held equal to the generator's current output by
// spec/ir_dispatch_words_export_spec.rb.

pub const BLUEBOOK_WORDS: &[(&str, &str)] = &[
    ("aggregate", "Aggregate"),
    ("policy", "Policy"),
    ("process_manager", "ProcessManager"),
    ("read_model", "ReadModel"),
];

pub const AGGREGATE_WORDS: &[(&str, &str)] = &[
    ("command", "Command"),
    ("entity", "Entity"),
    ("policy", "Policy"),
    ("query", "Query"),
    ("value_object", "ValueObject"),
];

