// GENERATED BY bin/ir_syntax_bindings — DO NOT EDIT BY HAND.
//
// Every (keyword, context) pair's own argument-binding shape, projected
// from the language's own declared syntax (Syntax::Keyword, Syntax::Argument
// — language/bluebook/syntax.bluebook). `append_to` is "" when this
// keyword's own bindings set fields directly on whatever construct is
// already being built, or names the LIST field a new compound gets
// appended to otherwise — computed by cross-referencing Syntax::Keyword's
// own `fills` against the enclosing category's declared field type, not
// carried by the language as a separate fact.
//
// EXCLUDED: any `pairs_shape: "sibling"` argument (`member`, `sets`'
// `append:` — see this file's own generator comment), and `.hecksagon`/
// `.world`'s open adapter-verb vocabulary.
//
// Source: lib/hecksagain/language/bluebook/syntax.bluebook
// Regenerate: bin/ir_syntax_bindings > rust/src/bluebook/ir_syntax_bindings.rs
//
// Held equal to the generator's current output by
// spec/ir_syntax_bindings_export_spec.rb.

#[derive(Debug, Clone, Copy)]
pub struct ArgumentBinding {
    pub at: &'static str,
    pub named: &'static str,
    pub kind: &'static str,
    pub required: bool,
    pub fills: &'static str,
    pub selects: &'static str,
    pub pair_key_fills: &'static str,
    pub pair_value_fills: &'static str,
    pub pairs_shape: &'static str,
}

#[derive(Debug, Clone, Copy)]
pub struct KeywordBinding {
    pub keyword: &'static str,
    pub context: &'static str,
    pub append_to: &'static str,
    pub arguments: &'static [ArgumentBinding],
}

pub const KEYWORD_BINDINGS: &[KeywordBinding] = &[
KeywordBinding {
    keyword: "attribute", context: "Aggregate", append_to: "attributes",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "symbol", required: true, fills: "name", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
        ArgumentBinding { at: "2", named: "", kind: "constant", required: false, fills: "type", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
        ArgumentBinding { at: "", named: "admits", kind: "text", required: false, fills: "admits", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
        ArgumentBinding { at: "", named: "default", kind: "literal", required: false, fills: "default", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
        ArgumentBinding { at: "", named: "optional", kind: "flag", required: false, fills: "optional", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
        ArgumentBinding { at: "", named: "pattern", kind: "text", required: false, fills: "pattern", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "belongs_to", context: "Aggregate", append_to: "attributes",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "constant", required: true, fills: "type", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
        ArgumentBinding { at: "", named: "as", kind: "symbol", required: false, fills: "name", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "command", context: "Aggregate", append_to: "",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "text", required: true, fills: "name", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "description", context: "Aggregate", append_to: "",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "text", required: true, fills: "description", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "entity", context: "Aggregate", append_to: "",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "text", required: true, fills: "name", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "has_many", context: "Aggregate", append_to: "attributes",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "constant", required: true, fills: "type", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
        ArgumentBinding { at: "", named: "as", kind: "symbol", required: false, fills: "name", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "has_one", context: "Aggregate", append_to: "attributes",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "constant", required: true, fills: "type", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
        ArgumentBinding { at: "", named: "as", kind: "symbol", required: false, fills: "name", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "lifecycle", context: "Aggregate", append_to: "",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "symbol", required: true, fills: "state_field", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
        ArgumentBinding { at: "", named: "default", kind: "literal", required: true, fills: "state_start", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "policy", context: "Aggregate", append_to: "",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "text", required: true, fills: "name", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "query", context: "Aggregate", append_to: "",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "text", required: true, fills: "name", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "reference_to", context: "Aggregate", append_to: "attributes",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "constant", required: true, fills: "type", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
        ArgumentBinding { at: "", named: "as", kind: "symbol", required: false, fills: "name", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "value_object", context: "Aggregate", append_to: "value_objects",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "text", required: true, fills: "name", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "aggregate", context: "Bluebook", append_to: "",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "text", required: true, fills: "name", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "policy", context: "Bluebook", append_to: "",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "text", required: true, fills: "name", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "process_manager", context: "Bluebook", append_to: "",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "text", required: true, fills: "name", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "read_model", context: "Bluebook", append_to: "",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "text", required: true, fills: "name", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "vision", context: "Bluebook", append_to: "",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "text", required: true, fills: "vision", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "attribute", context: "Command", append_to: "attributes",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "symbol", required: true, fills: "name", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
        ArgumentBinding { at: "2", named: "", kind: "constant", required: false, fills: "type", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
        ArgumentBinding { at: "", named: "admits", kind: "text", required: false, fills: "admits", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
        ArgumentBinding { at: "", named: "default", kind: "literal", required: false, fills: "default", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
        ArgumentBinding { at: "", named: "optional", kind: "flag", required: false, fills: "optional", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
        ArgumentBinding { at: "", named: "pattern", kind: "text", required: false, fills: "pattern", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "emits", context: "Command", append_to: "emits",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "text", required: true, fills: "emits", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "given", context: "Command", append_to: "givens",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "text", required: true, fills: "description", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "goal", context: "Command", append_to: "",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "text", required: true, fills: "goal", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "reference_to", context: "Command", append_to: "",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "constant", required: true, fills: "type", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
        ArgumentBinding { at: "", named: "as", kind: "symbol", required: false, fills: "name", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
        ArgumentBinding { at: "", named: "optional", kind: "flag", required: false, fills: "optional", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "role", context: "Command", append_to: "",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "text", required: true, fills: "role", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "sets", context: "Command", append_to: "mutations",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "symbol", required: true, fills: "target", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
        ArgumentBinding { at: "", named: "decrement", kind: "symbol", required: false, fills: "source", selects: "op=decrement", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
        ArgumentBinding { at: "", named: "increment", kind: "symbol", required: false, fills: "source", selects: "op=increment", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
        ArgumentBinding { at: "", named: "to", kind: "symbol", required: false, fills: "source", selects: "op=set", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "attribute", context: "Entity", append_to: "attributes",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "symbol", required: true, fills: "name", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
        ArgumentBinding { at: "2", named: "", kind: "constant", required: false, fills: "type", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
        ArgumentBinding { at: "", named: "admits", kind: "text", required: false, fills: "admits", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
        ArgumentBinding { at: "", named: "default", kind: "literal", required: false, fills: "default", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
        ArgumentBinding { at: "", named: "optional", kind: "flag", required: false, fills: "optional", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
        ArgumentBinding { at: "", named: "pattern", kind: "text", required: false, fills: "pattern", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "command", context: "Entity", append_to: "",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "text", required: true, fills: "name", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "description", context: "Entity", append_to: "",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "text", required: true, fills: "description", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "lifecycle", context: "Entity", append_to: "",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "symbol", required: true, fills: "state_field", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
        ArgumentBinding { at: "", named: "default", kind: "literal", required: true, fills: "state_start", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "query", context: "Entity", append_to: "",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "text", required: true, fills: "name", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "bluebook", context: "File", append_to: "",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "text", required: true, fills: "name", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
        ArgumentBinding { at: "", named: "version", kind: "text", required: false, fills: "version", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "hecksagon", context: "File", append_to: "",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "text", required: true, fills: "domain", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "world", context: "File", append_to: "",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "text", required: true, fills: "domain", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "dispatch", context: "Handler", append_to: "",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "text", required: true, fills: "command_name", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
        ArgumentBinding { at: "", named: "with", kind: "pairs", required: false, fills: "with_spec", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "verbatim" },
    ],
},
KeywordBinding {
    keyword: "transition", context: "Lifecycle", append_to: "transitions",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "pairs", required: true, fills: "", selects: "", pair_key_fills: "command", pair_value_fills: "to_state", pairs_shape: "fields" },
        ArgumentBinding { at: "", named: "from", kind: "text", required: false, fills: "from_state", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
        ArgumentBinding { at: "", named: "from", kind: "list", required: false, fills: "from_state", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "across", context: "Policy", append_to: "",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "text", required: true, fills: "target_domain", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "on", context: "Policy", append_to: "",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "text", required: true, fills: "on_event", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "trigger", context: "Policy", append_to: "",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "text", required: true, fills: "trigger_command", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "correlates_by", context: "ProcessManager", append_to: "",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "symbol", required: true, fills: "correlates_by", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "ends_on", context: "ProcessManager", append_to: "",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "text", required: true, fills: "ends_on", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "on", context: "ProcessManager", append_to: "",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "text", required: true, fills: "event_type", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
        ArgumentBinding { at: "", named: "transition", kind: "pairs", required: true, fills: "", selects: "", pair_key_fills: "from_state", pair_value_fills: "to_state", pairs_shape: "fields" },
    ],
},
KeywordBinding {
    keyword: "starts_on", context: "ProcessManager", append_to: "",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "text", required: true, fills: "starts_on", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "state", context: "ProcessManager", append_to: "states",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "text", required: true, fills: "states", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "attribute", context: "Query", append_to: "attributes",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "symbol", required: true, fills: "name", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
        ArgumentBinding { at: "2", named: "", kind: "constant", required: false, fills: "type", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
        ArgumentBinding { at: "", named: "admits", kind: "text", required: false, fills: "admits", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
        ArgumentBinding { at: "", named: "default", kind: "literal", required: false, fills: "default", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
        ArgumentBinding { at: "", named: "optional", kind: "flag", required: false, fills: "optional", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
        ArgumentBinding { at: "", named: "pattern", kind: "text", required: false, fills: "pattern", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "authorize", context: "Query", append_to: "options",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "symbol", required: true, fills: "policy", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
        ArgumentBinding { at: "", named: "tenant", kind: "symbol", required: false, fills: "tenant", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "consistency", context: "Query", append_to: "options",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "symbol", required: true, fills: "mode", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
        ArgumentBinding { at: "", named: "timeout", kind: "number", required: false, fills: "timeout", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "cursor", context: "Query", append_to: "options",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "symbol", required: true, fills: "value", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "description", context: "Query", append_to: "",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "text", required: true, fills: "description", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "freshness", context: "Query", append_to: "options",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "symbol", required: true, fills: "mode", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
        ArgumentBinding { at: "", named: "max_age", kind: "number", required: false, fills: "max_age", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "inspect_query", context: "Query", append_to: "options",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "symbol", required: false, fills: "mode", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "limit", context: "Query", append_to: "",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "number", required: true, fills: "limit", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "nulls", context: "Query", append_to: "options",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "symbol", required: true, fills: "mode", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "offset", context: "Query", append_to: "options",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "number", required: true, fills: "value", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "order_by", context: "Query", append_to: "",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "symbol", required: true, fills: "order_field", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
        ArgumentBinding { at: "2", named: "", kind: "symbol", required: false, fills: "order_way", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "use_index", context: "Query", append_to: "options",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "symbol", required: true, fills: "name", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "where", context: "Query", append_to: "wheres",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "pairs", required: true, fills: "wheres", selects: "", pair_key_fills: "field", pair_value_fills: "value", pairs_shape: "elements" },
    ],
},
KeywordBinding {
    keyword: "authorize", context: "ReadModel", append_to: "options",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "symbol", required: true, fills: "policy", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
        ArgumentBinding { at: "", named: "tenant", kind: "symbol", required: false, fills: "tenant", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "consistency", context: "ReadModel", append_to: "options",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "symbol", required: true, fills: "mode", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
        ArgumentBinding { at: "", named: "timeout", kind: "number", required: false, fills: "timeout", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "cursor", context: "ReadModel", append_to: "options",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "symbol", required: true, fills: "value", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "description", context: "ReadModel", append_to: "",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "text", required: true, fills: "description", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "freshness", context: "ReadModel", append_to: "options",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "symbol", required: true, fills: "mode", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
        ArgumentBinding { at: "", named: "max_age", kind: "number", required: false, fills: "max_age", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "include", context: "ReadModel", append_to: "aggregate_heads",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "constant", required: true, fills: "aggregate", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
        ArgumentBinding { at: "", named: "as", kind: "symbol", required: false, fills: "as", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "inspect_query", context: "ReadModel", append_to: "options",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "symbol", required: false, fills: "mode", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "limit", context: "ReadModel", append_to: "options",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "number", required: true, fills: "value", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "nulls", context: "ReadModel", append_to: "options",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "symbol", required: true, fills: "mode", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "offset", context: "ReadModel", append_to: "options",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "number", required: true, fills: "value", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "order_by", context: "ReadModel", append_to: "options",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "symbol", required: true, fills: "field", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
        ArgumentBinding { at: "2", named: "", kind: "symbol", required: false, fills: "direction", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "reference_to", context: "ReadModel", append_to: "",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "constant", required: true, fills: "reference_target", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
        ArgumentBinding { at: "", named: "as", kind: "symbol", required: false, fills: "reference_name", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "use_index", context: "ReadModel", append_to: "options",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "symbol", required: true, fills: "name", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "where", context: "ReadModel", append_to: "options",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "pairs", required: true, fills: "", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "list_of", context: "Type", append_to: "",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "constant", required: true, fills: "", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "one_of", context: "Type", append_to: "",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "literal", required: true, fills: "", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "attribute", context: "ValueObject", append_to: "attributes",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "symbol", required: true, fills: "name", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
        ArgumentBinding { at: "2", named: "", kind: "constant", required: false, fills: "type", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
        ArgumentBinding { at: "", named: "admits", kind: "text", required: false, fills: "admits", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
        ArgumentBinding { at: "", named: "default", kind: "literal", required: false, fills: "default", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
        ArgumentBinding { at: "", named: "optional", kind: "flag", required: false, fills: "optional", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
        ArgumentBinding { at: "", named: "pattern", kind: "text", required: false, fills: "pattern", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
KeywordBinding {
    keyword: "invariant", context: "ValueObject", append_to: "invariants",
    arguments: &[
        ArgumentBinding { at: "1", named: "", kind: "text", required: true, fills: "description", selects: "", pair_key_fills: "", pair_value_fills: "", pairs_shape: "" },
    ],
},
];
