// GENERATED BY bin/ir_syntax_flags — DO NOT EDIT BY HAND.
//
// Every named argument the language declares as kind "flag" — read as a
// bare true/false, never a quoted string or a bare word.
// Source: lib/hecksagain/language/bluebook/syntax.bluebook
// Regenerate: bin/ir_syntax_flags > rust/src/bluebook/ir_syntax_flags.rs
//
// Held equal to the generator's current output by
// spec/ir_syntax_flags_export_spec.rb. Checked at every call by
// parse_flag_kwarg itself (parse_blocks.rs) — a kwarg name reaching that
// function which this table does not list is a reader/declaration
// mismatch, not a missing feature, and it asserts rather than silently
// mis-parsing.

pub const FLAG_ARGUMENTS: &[&str] = &[
    "optional",
];
