// GENERATED BY bin/ir_syntax — DO NOT EDIT BY HAND.
//
// Which words open a `do` block at AGGREGATE-BODY level, projected from the
// language's own declared syntax.
// Source: lib/hecksagain/language/bluebook/syntax.bluebook (Syntax::Keyword,
// rows where context = "Aggregate" and body is "keywords" or "source").
// Regenerate: bin/ir_syntax > rust/src/bluebook/ir_syntax.rs
//
// Held equal to the generator's current output by
// spec/ir_syntax_export_spec.rb, and held equal to the language's own
// declaration (in both directions) by spec/syntax_conformance_spec.rb — so
// this list cannot drift from what a bluebook may actually type the way the
// hand-written copy in runtime::strict_boot did.

pub const BLOCK_KEYWORDS: &[&str] = &[
    "command",
    "entity",
    "identified_by",
    "lifecycle",
    "policy",
    "query",
    "value_object",
];
