// GENERATED BY bin/ir_structs — DO NOT EDIT BY HAND.
//
// The shapes the language declares about itself, projected into Rust structs.
// Sources: lib/hecksagain/language/bluebook/*.bluebook (the thirteen
// categories) and lib/hecksagain/bluebook/assembly/contracts.rb (the fold
// table — which declared fields the IR does not carry, and why).
// Regenerate: bin/ir_structs > rust/src/bluebook/ir_structs.rs
//
// Held equal to the generator's current output by
// spec/ir_structs_export_spec.rb, so a forgotten regeneration goes red rather
// than compiling a stale copy of a shape the language has since changed.
//
// WHAT IS NOT HERE, AND WHY. These stay hand-written in ir.rs. A generator
// that reached them would need a rule bigger than the struct, or would have to
// invent what the language does not say — so each is named with its reason,
// and each DIVERGENCE below is a real disagreement between the language and
// Rust that is worth closing at one end or the other:
//
//   Lifecycle
//     a DECLARED FOLD — the language holds state_field/state_start/transitions
//     flat on Aggregate and Entity, and contracts.rb folds them into this. The
//     fold's TARGET is generatable (both structs get `lifecycle:
//     Option<Lifecycle>`); the struct it targets is not.
//
//   OrderBy
//     the same fold, one category over — Query holds order_field/order_way
//     flat.
//
//   Direction
//     no language source. `order_way` is a QueryText, not a closed set;
//     Vocabulary never declares the two directions.
//
//   LimitSpec
//     no language source. Query.limit is a QueryText — a plain string — so the
//     language would project `Option<String>`, not a struct.
//
//   ValueSpec
//     no language source at all. from_event/from_pm/from_iter are a Rust-side
//     reading of a dispatch binding; the language declares Binding as two plain
//     strings.
//
//   Query
//     DIVERGENCE — `limit`. The language declares Query.limit as QueryText
//     (optional on Declare), which projects to Option<String>; Rust holds
//     Option<LimitSpec>. Everything else in Query projects exactly.
//
//   ValueObject
//     DIVERGENCE — `members` and `closed_set`. The language models a member as
//     its OWN root (the Member category, with an open map of pairs) and keeps
//     only a `rows` COUNT on ValueObject; Rust holds the rows themselves plus a
//     bool. contracts.rb marks `rows` as folded FROM closed_set+members, which
//     is the fold running backwards — the language cannot hand back what it
//     only counted.
//
//   Policy
//     DIVERGENCE — `aggregate`. The language declares it and Ruby's IR::Policy
//     carries it (which head the policy was WRITTEN inside, before the builder
//     hoisted it onto the chapter), but Ruby keeps it off `to_h` on purpose:
//     the wire is the contract between the runtimes and does not carry it. So
//     Rust never grew the field. Projecting it would put a field on Rust that
//     nothing can fill from the wire — the asymmetry is deliberate, and it is
//     Ruby's comment, not this generator's, that should decide when it ends.
//
//   DispatchSpec
//     DIVERGENCE — `with_spec`. The language declares list_of(Binding) where
//     Binding is two plain strings, so it projects to Vec<Binding>; Rust holds
//     Vec<(String, ValueSpec)> and reads each value as a
//     from_event/from_pm/literal spec.
//
//   Attribute
//     DIVERGENCE — `enum_values`, and the flags. The language declares seven
//     plain-String fields (name/type/list/optional/pattern/default/admits) and
//     Rust carries all seven — `admits` reached the wire once it became a RULE
//     both runtimes enforce, and this generator reads it to type a field
//     besides (see WhereClause). Rust also carries `enum_values: Vec<String>`
//     the language never declares, and reads `list`/`optional` as bool where
//     the language admits only Strings. The five element declarations now agree
//     that `pattern` and `default` are free text — Aggregate's three builders
//     typed `pattern` as a ListFlag, which admits only "true"/"false" and so
//     was false about a regex rather than merely loose — but they still
//     disagree about `name`, `type` and the two flags, so no single type rule
//     reads all five.
//
//   Invariant
//     DIVERGENCE — `description`. `Command::Rule` and `ValueObject::Assertion`
//     are byte-identical declarations built by byte-identical commands
//     (description OPTIONAL, canonical required), yet Rust holds
//     Given.description as Option<String> and Invariant.description as String.
//     The dedupe rule says these are one struct; Rust says they are two. Given
//     is projected, Invariant is not.
//
//   Mutation
//     DIVERGENCE — arity. The language declares Change with five fields
//     (target, op, field, kind, source); Rust's Mutation carries three (target,
//     op, source) and types op as the MutationOp closed set. `field` and `kind`
//     are declared and unread.
//
//   AggregateHead
//     DIVERGENCE — `many`. The language declares it as a plain ReadModelText
//     and Rust reads it as a bool, with no ListFlag-style invariant behind it
//     to read. `aggregate` used to be the second half of this: declared
//     OPTIONAL on ReadModel.Gather against Rust's required String, and neither
//     runtime can build a head without one, so the language was corrected and
//     only the flag is left.

use super::ir::{AggregateHead, Attribute, DispatchSpec, Lifecycle, Mutation, Policy, Query, ValueObject, WhereOp};

/// `Command::Rule`, as the language declares it.
#[derive(Debug, Clone)]
pub struct Given {
    /// String, optional on Command.Rule
    pub description: Option<String>,
    /// String, required on Command.Rule
    pub canonical: String,
}

/// `Aggregate::Transition`, as the language declares it.
#[derive(Debug, Clone)]
pub struct Transition {
    /// String, required on Aggregate.Transition
    pub command: String,
    /// String, optional on Aggregate.Transition
    pub from_state: Option<String>,
    /// String, required on Aggregate.Transition
    pub to_state: String,
}

/// `Query::Filter`, as the language declares it.
#[derive(Debug, Clone)]
pub struct WhereClause {
    /// String, required on Query.Filter
    pub field: String,
    /// String, admits Vocabulary::QueryComparator, required on Query.Filter
    pub op: WhereOp,
    /// String, required on Query.Filter
    pub value: String,
}

/// `Bluebook::Bluebook`, as the language declares it.
#[derive(Debug, Clone)]
pub struct Domain {
    /// BluebookName
    pub name: String,
    /// Vision
    pub vision: Option<String>,
    /// Classification
    pub classification: Option<String>,
    /// Version
    pub version: Option<String>,
    /// every Aggregate whose parent this is
    pub aggregates: Vec<Aggregate>,
    /// every Policy whose parent this is
    pub policies: Vec<Policy>,
    /// every ProcessManager whose parent this is
    pub process_managers: Vec<ProcessManager>,
    /// every ReadModel whose parent this is
    pub read_models: Vec<ReadModel>,
}

/// `Bluebook::Aggregate`, as the language declares it.
#[derive(Debug, Clone)]
pub struct Aggregate {
    /// AggregateName
    pub name: String,
    /// Description
    pub description: Option<String>,
    /// list_of(IdentityPath)
    pub identified_by: Vec<String>,
    /// list_of(Field)
    pub attributes: Vec<Attribute>,
    /// declared fold
    pub lifecycle: Option<Lifecycle>,
    /// every Command whose parent this is
    pub commands: Vec<Command>,
    /// every Query whose parent this is
    pub queries: Vec<Query>,
    /// every ValueObject whose parent this is
    pub value_objects: Vec<ValueObject>,
    /// every Entity whose parent this is
    pub entities: Vec<Entity>,
}

/// `Bluebook::Entity`, as the language declares it.
#[derive(Debug, Clone)]
pub struct Entity {
    /// EntityName
    pub name: String,
    /// EntityName
    pub description: Option<String>,
    /// list_of(IdentityPath)
    pub identified_by: Vec<String>,
    /// list_of(PieceField)
    pub attributes: Vec<Attribute>,
    /// declared fold
    pub lifecycle: Option<Lifecycle>,
    /// every Command whose parent this is
    pub commands: Vec<Command>,
    /// every Query whose parent this is
    pub queries: Vec<Query>,
}

/// `Bluebook::Command`, as the language declares it.
#[derive(Debug, Clone)]
pub struct Command {
    /// CommandName
    pub name: String,
    /// Actor
    pub role: Option<String>,
    /// Goal
    pub goal: Option<String>,
    /// list_of(Announcement)
    pub emits: Vec<String>,
    /// EventName
    pub references: Option<String>,
    /// list_of(Argument)
    pub attributes: Vec<Attribute>,
    /// list_of(Rule)
    pub givens: Vec<Given>,
    /// list_of(Change)
    pub mutations: Vec<Mutation>,
}

/// `Bluebook::ReadModel`, as the language declares it.
#[derive(Debug, Clone)]
pub struct ReadModel {
    /// ReadModelName
    pub name: String,
    /// ProjectionPurpose
    pub description: Option<String>,
    /// ReadModelText
    pub reference_name: String,
    /// ReadModelText
    pub reference_target: String,
    /// list_of(Head)
    pub aggregate_heads: Vec<AggregateHead>,
}

/// `Bluebook::ProcessManager`, as the language declares it.
#[derive(Debug, Clone)]
pub struct ProcessManager {
    /// ProcessManagerName
    pub name: String,
    /// ProcessManagerText
    pub correlates_by: String,
    /// ProcessManagerText
    pub starts_on: String,
    /// ProcessManagerText
    pub ends_on: Option<String>,
    /// list_of(SagaState)
    pub states: Vec<String>,
    /// every Handler whose parent this is
    pub handlers: Vec<ProcessManagerHandler>,
}

/// `Bluebook::Handler`, as the language declares it.
#[derive(Debug, Clone)]
pub struct ProcessManagerHandler {
    /// HandlerText
    pub event_type: String,
    /// HandlerText
    pub from_state: String,
    /// HandlerText
    pub to_state: String,
    /// every Dispatch whose parent this is
    pub dispatches: Vec<DispatchSpec>,
}
