// GENERATED BY bin/ir_syntax_number — DO NOT EDIT BY HAND.
//
// Every named argument the language declares as kind "number" — a bare
// numeric word.
// Source: lib/hecksagain/language/bluebook/syntax.bluebook
// Regenerate: bin/ir_syntax_number > rust/src/bluebook/ir_syntax_number.rs
//
// Held equal to the generator's current output by
// spec/ir_syntax_number_export_spec.rb. Checked at every call by
// assert_number_kwarg itself (parse_blocks.rs) — a kwarg name reaching
// that assertion which this table does not list is a reader/declaration
// mismatch, not a missing feature.

pub const NUMBER_ARGUMENTS: &[&str] = &[
    "max_age",
    "timeout",
];
