// GENERATED BY bin/ir_syntax_text — DO NOT EDIT BY HAND.
//
// Every named argument the language declares as kind "text" — a quoted
// string, read as-is. `from:` is declared but excluded: it is ALSO kind
// "list" at the same keyword+context (transition's from: takes one state
// or several), so no single kind table can assert it correctly.
// Source: lib/hecksagain/language/bluebook/syntax.bluebook
// Regenerate: bin/ir_syntax_text > rust/src/bluebook/ir_syntax_text.rs
//
// Held equal to the generator's current output by
// spec/ir_syntax_text_export_spec.rb. Checked at every call by
// assert_text_kwarg itself (parse_blocks.rs) — a kwarg name reaching that
// assertion which this table does not list is a reader/declaration
// mismatch, not a missing feature.

pub const TEXT_ARGUMENTS: &[&str] = &[
    "admits",
    "pattern",
    "version",
];
