// GENERATED BY bin/ir_vocabulary — DO NOT EDIT BY HAND.
//
// The closed sets the language declares about itself, projected into Rust.
// Source: lib/hecksagain/language/bluebook/vocabulary.bluebook (Vocabulary).
// Regenerate: bin/ir_vocabulary > rust/src/bluebook/ir_vocabulary.rs
//
// Held equal to the generator's current output by
// spec/ir_vocabulary_export_spec.rb, and held equal to each runtime's live
// table by spec/vocabulary_conformance_spec.rb — so the language, Ruby and
// Rust cannot disagree about what these sets admit.

/// `Vocabulary::MutationOp`, as the language declares it.
#[derive(Debug, Clone)]
pub enum MutationOp {
    Set,
    Append,
    Increment,
    Decrement,
}

/// `Vocabulary::QueryComparator`, as the language declares it.
#[derive(Debug, Clone)]
pub enum WhereOp {
    Eq,
    Ne,
    Gt,
    Gte,
    Lt,
    Lte,
    In,
    Contains,
}
