# Hecks::Generators::Infrastructure::DomainGemGenerator
#
# Generates a complete domain gem — aggregates, queries, ports, adapters, specs.
#
require "fileutils"

module Hecks
  module Generators
    module Infrastructure
    class DomainGemGenerator
      def initialize(domain, version: "0.1.0", output_dir: ".")
        @domain = domain
        @version = version
        @output_dir = output_dir
      end

      def generate
        gem_name = @domain.gem_name
        mod = @domain.module_name + "Domain"
        root = File.join(@output_dir, gem_name)

        FileUtils.rm_rf(root)
        FileUtils.mkdir_p(root)

        generate_gemspec(root, gem_name, mod)
        generate_entry_point(root, gem_name, mod)
        generate_aggregates(root, gem_name, mod)
        generate_queries(root, gem_name, mod)
        generate_ports(root, gem_name, mod)
        generate_adapters(root, gem_name, mod)
        generate_specs(root, gem_name, mod)
        generate_domain_rb(root)

        root
      end

      AGGREGATE_GENERATORS = {
        value_objects: Domain::ValueObjectGenerator,
        commands:      Domain::CommandGenerator,
        events:        Domain::EventGenerator,
        policies:      Domain::PolicyGenerator,
      }.freeze

      # Generate all Ruby source as one eval-ready string (no file I/O).
      def generate_source
        mod = @domain.module_name + "Domain"
        [module_shell(mod), *aggregate_sources(mod)].join("\n")
      end

      private

      def generate_gemspec(root, gem_name, mod)
        write_file(root, "#{gem_name}.gemspec", <<~RUBY)
          Gem::Specification.new do |s|
            s.name = "#{gem_name}"; s.version = "#{@version}"
            s.authors = ["Generated by Hecks"]; s.summary = "#{@domain.name} domain model"
            s.description = "Pure domain gem generated by Hecks"; s.license = "MIT"
            s.files = Dir["lib/**/*", "docs/**/*", "hecks_domain.rb"]; s.require_paths = ["lib"]
            s.required_ruby_version = ">= 3.0"
            s.add_development_dependency "rspec", "~> 3.0"
          end
        RUBY
      end

      def generate_entry_point(root, gem_name, mod)
        write_file(root, "lib/#{gem_name}.rb", AutoloadGenerator.new(@domain).generate_entry_point)
      end

      def generate_aggregates(root, gem_name, mod)
        @domain.aggregates.each do |agg|
          safe_name = Hecks::Utils.sanitize_constant(agg.name)
          snake = Hecks::Utils.underscore(safe_name)
          base = "lib/#{gem_name}/#{snake}"

          # Aggregate root with embedded autoloads
          agg_gen = Domain::AggregateGenerator.new(agg, domain_module: mod)
          autoload_gen = AutoloadGenerator.new(@domain)
          autoloads = autoload_gen.generate_aggregate_autoloads(agg, gem_name, mod)

          agg_code = agg_gen.generate
          agg_code = inject_autoloads(agg_code, autoloads, safe_name)

          write_file(root, "#{base}/#{snake}.rb", agg_code)

          # Value objects
          agg.value_objects.each do |vo|
            vo_gen = Domain::ValueObjectGenerator.new(vo, domain_module: mod, aggregate_name: safe_name)
            write_file(root, "#{base}/#{Hecks::Utils.underscore(vo.name)}.rb", vo_gen.generate)
          end

          # Commands
          agg.commands.each do |cmd|
            cmd_gen = Domain::CommandGenerator.new(cmd, domain_module: mod, aggregate_name: safe_name)
            write_file(root, "#{base}/commands/#{Hecks::Utils.underscore(cmd.name)}.rb", cmd_gen.generate)
          end

          # Events
          agg.events.each do |evt|
            evt_gen = Domain::EventGenerator.new(evt, domain_module: mod, aggregate_name: safe_name)
            write_file(root, "#{base}/events/#{Hecks::Utils.underscore(evt.name)}.rb", evt_gen.generate)
          end

          # Policies
          agg.policies.each do |pol|
            pol_gen = Domain::PolicyGenerator.new(pol, domain_module: mod, aggregate_name: safe_name)
            write_file(root, "#{base}/policies/#{Hecks::Utils.underscore(pol.name)}.rb", pol_gen.generate)
          end
        end
      end

      def generate_queries(root, gem_name, mod)
        @domain.aggregates.each do |agg|
          safe = Hecks::Utils.sanitize_constant(agg.name)
          snake = Hecks::Utils.underscore(safe)
          agg.queries.each do |q|
            write_file(root, "lib/#{gem_name}/#{snake}/queries/#{Hecks::Utils.underscore(q.name)}.rb",
                       Domain::QueryGenerator.new(q, domain_module: mod, aggregate_name: safe).generate)
          end
        end
      end

      def generate_ports(root, gem_name, mod)
        @domain.aggregates.each do |agg|
          snake = Hecks::Utils.underscore(Hecks::Utils.sanitize_constant(agg.name))
          write_file(root, "lib/#{gem_name}/ports/#{snake}_repository.rb",
                     Infrastructure::PortGenerator.new(agg, domain_module: mod).generate)
        end
      end

      def generate_adapters(root, gem_name, mod)
        @domain.aggregates.each do |agg|
          snake = Hecks::Utils.underscore(Hecks::Utils.sanitize_constant(agg.name))
          write_file(root, "lib/#{gem_name}/adapters/#{snake}_memory_repository.rb",
                     Infrastructure::MemoryAdapterGenerator.new(agg, domain_module: mod).generate)
        end
      end

      def module_shell(mod)
        "require 'securerandom'\nmodule #{mod}\n  class ValidationError < StandardError; end\n  class InvariantError < StandardError; end\nend"
      end

      def aggregate_sources(mod)
        parts = []
        @domain.aggregates.each do |agg|
          safe_name = Hecks::Utils.sanitize_constant(agg.name)
          opts = { domain_module: mod }
          parts << source_for(Domain::AggregateGenerator, agg, **opts)
          AGGREGATE_GENERATORS.each do |method, gen|
            agg.send(method).each { |obj| parts << source_for(gen, obj, aggregate_name: safe_name, **opts) }
          end
          parts << source_for(Infrastructure::PortGenerator, agg, **opts)
          parts << source_for(Infrastructure::MemoryAdapterGenerator, agg, **opts)
        end
        parts
      end

      def source_for(klass, obj, **opts) = klass.new(obj, **opts).generate

      def generate_specs(root, gem_name, mod)
        sg = SpecGenerator.new(@domain)
        write_file(root, "spec/spec_helper.rb", sg.generate_spec_helper)
        write_file(root, ".rspec", "--format documentation\n--color\n--require spec_helper\n")
        @domain.aggregates.each do |agg|
          snake = Hecks::Utils.underscore(Hecks::Utils.sanitize_constant(agg.name))
          write_file(root, "spec/#{snake}/#{snake}_spec.rb", sg.generate_aggregate_spec(agg))
          agg.value_objects.each do |vo|
            write_file(root, "spec/#{snake}/#{Hecks::Utils.underscore(vo.name)}_spec.rb", sg.generate_value_object_spec(vo, agg))
          end
          agg.commands.each do |cmd|
            write_file(root, "spec/#{snake}/commands/#{Hecks::Utils.underscore(cmd.name)}_spec.rb", sg.generate_command_spec(cmd, agg))
          end
          agg.events.each do |evt|
            write_file(root, "spec/#{snake}/events/#{Hecks::Utils.underscore(evt.name)}_spec.rb", sg.generate_event_spec(evt, agg))
          end
        end
      end

      def generate_domain_rb(root)
        dsl = DslSerializer.new(@domain).serialize
        write_file(root, "hecks_domain.rb", dsl)
      end

      def inject_autoloads(code, autoloads, agg_name)
        return code if autoloads.strip.empty?

        marker = "class #{agg_name}\n"
        code.sub(marker, "#{marker}#{autoloads}\n\n")
      end

      def write_file(root, relative_path, content)
        path = File.join(root, relative_path)
        FileUtils.mkdir_p(File.dirname(path))
        File.write(path, content)
      end

    end
    end
  end
end
