# Hecks::Generators::Infrastructure::DomainGemGenerator
#
# Generates a complete domain gem — aggregates, queries, ports, adapters, specs.
#
require "fileutils"

module Hecks
  module Generators
    module Infrastructure
    class DomainGemGenerator
      def initialize(domain, version: "0.1.0", output_dir: ".")
        @domain = domain
        @version = version
        @output_dir = output_dir
      end

      def generate
        gem_name = @domain.gem_name
        mod = @domain.module_name + "Domain"
        root = File.join(@output_dir, gem_name)

        FileUtils.rm_rf(root)
        FileUtils.mkdir_p(root)

        generate_gemspec(root, gem_name, mod)
        generate_entry_point(root, gem_name, mod)
        generate_aggregates(root, gem_name, mod)
        generate_queries(root, gem_name, mod)
        generate_ports(root, gem_name, mod)
        generate_adapters(root, gem_name, mod)
        generate_specs(root, gem_name, mod)
        generate_domain_rb(root)

        root
      end

      private

      def generate_gemspec(root, gem_name, mod)
        write_file(root, "#{gem_name}.gemspec", <<~RUBY)
          Gem::Specification.new do |spec|
            spec.name          = "#{gem_name}"
            spec.version       = "#{@version}"
            spec.authors       = ["Generated by Hecks"]
            spec.summary       = "#{@domain.name} domain model"
            spec.description   = "Pure domain gem generated by Hecks"
            spec.license       = "MIT"

            spec.files         = Dir["lib/**/*", "docs/**/*", "domain.rb"]
            spec.require_paths = ["lib"]

            spec.required_ruby_version = ">= 3.0"

            spec.add_development_dependency "rspec", "~> 3.0"
          end
        RUBY
      end

      def generate_entry_point(root, gem_name, mod)
        autoload_gen = AutoloadGenerator.new(@domain)
        write_file(root, "lib/#{gem_name}.rb", autoload_gen.generate_entry_point)
      end

      def generate_aggregates(root, gem_name, mod)
        @domain.contexts.each do |ctx|
          ctx_mod = ctx.default? ? nil : ctx.module_name

          ctx.aggregates.each do |agg|
            snake = Hecks::Utils.underscore(agg.name)
            ctx_prefix = ctx.default? ? "" : "#{Hecks::Utils.underscore(ctx.module_name)}/"
            base = "lib/#{gem_name}/#{ctx_prefix}#{snake}"

            # Aggregate root with embedded autoloads
            agg_gen = Domain::AggregateGenerator.new(agg, domain_module: mod, context_module: ctx_mod)
            autoload_gen = AutoloadGenerator.new(@domain)
            autoloads = autoload_gen.generate_aggregate_autoloads(agg, gem_name, mod, context: ctx)

            agg_code = agg_gen.generate
            agg_code = inject_autoloads(agg_code, autoloads, agg.name, ctx_mod)

            write_file(root, "#{base}/#{snake}.rb", agg_code)

            # Value objects
            agg.value_objects.each do |vo|
              vo_gen = Domain::ValueObjectGenerator.new(vo, domain_module: mod, aggregate_name: agg.name, context_module: ctx_mod)
              write_file(root, "#{base}/#{Hecks::Utils.underscore(vo.name)}.rb", vo_gen.generate)
            end

            # Commands
            agg.commands.each do |cmd|
              cmd_gen = Domain::CommandGenerator.new(cmd, domain_module: mod, aggregate_name: agg.name, context_module: ctx_mod)
              write_file(root, "#{base}/commands/#{Hecks::Utils.underscore(cmd.name)}.rb", cmd_gen.generate)
            end

            # Events
            agg.events.each do |evt|
              evt_gen = Domain::EventGenerator.new(evt, domain_module: mod, aggregate_name: agg.name, context_module: ctx_mod)
              write_file(root, "#{base}/events/#{Hecks::Utils.underscore(evt.name)}.rb", evt_gen.generate)
            end

            # Policies
            agg.policies.each do |pol|
              pol_gen = Domain::PolicyGenerator.new(pol, domain_module: mod, aggregate_name: agg.name, context_module: ctx_mod)
              write_file(root, "#{base}/policies/#{Hecks::Utils.underscore(pol.name)}.rb", pol_gen.generate)
            end
          end
        end
      end

      def generate_queries(root, gem_name, mod)
        each_aggregate_with_context do |agg, ctx_mod, ctx_prefix|
          snake = Hecks::Utils.underscore(agg.name)
          agg.queries.each do |query|
            query_gen = Domain::QueryGenerator.new(query, domain_module: mod, aggregate_name: agg.name, context_module: ctx_mod)
            write_file(root, "lib/#{gem_name}/#{ctx_prefix}#{snake}/queries/#{Hecks::Utils.underscore(query.name)}.rb", query_gen.generate)
          end
        end
      end

      def generate_ports(root, gem_name, mod)
        each_aggregate_with_context do |agg, ctx_mod, ctx_prefix|
          port_gen = Infrastructure::PortGenerator.new(agg, domain_module: mod, context_module: ctx_mod)
          write_file(root, "lib/#{gem_name}/ports/#{ctx_prefix}#{Hecks::Utils.underscore(agg.name)}_repository.rb", port_gen.generate)
        end
      end

      def generate_adapters(root, gem_name, mod)
        each_aggregate_with_context do |agg, ctx_mod, ctx_prefix|
          adapter_gen = Infrastructure::MemoryAdapterGenerator.new(agg, domain_module: mod, context_module: ctx_mod)
          write_file(root, "lib/#{gem_name}/adapters/#{ctx_prefix}#{Hecks::Utils.underscore(agg.name)}_memory_repository.rb", adapter_gen.generate)
        end
      end

      def each_aggregate_with_context
        @domain.contexts.each do |ctx|
          ctx_mod = ctx.default? ? nil : ctx.module_name
          ctx_prefix = ctx.default? ? "" : "#{Hecks::Utils.underscore(ctx.module_name)}/"
          ctx.aggregates.each { |agg| yield agg, ctx_mod, ctx_prefix }
        end
      end

      def generate_specs(root, gem_name, mod)
        spec_gen = SpecGenerator.new(@domain)

        write_file(root, "spec/spec_helper.rb", spec_gen.generate_spec_helper)
        write_file(root, ".rspec", "--format documentation\n--color\n--require spec_helper\n")

        @domain.contexts.each do |ctx|
          ctx_prefix = ctx.default? ? "" : "#{Hecks::Utils.underscore(ctx.module_name)}/"
          ctx_mod = ctx.default? ? nil : ctx.module_name

          ctx.aggregates.each do |agg|
            snake = Hecks::Utils.underscore(agg.name)

            write_file(root, "spec/#{ctx_prefix}#{snake}/#{snake}_spec.rb",
                       spec_gen.generate_aggregate_spec(agg, context_module: ctx_mod))

            agg.value_objects.each do |vo|
              write_file(root, "spec/#{ctx_prefix}#{snake}/#{Hecks::Utils.underscore(vo.name)}_spec.rb",
                         spec_gen.generate_value_object_spec(vo, agg, context_module: ctx_mod))
            end

            agg.commands.each do |cmd|
              write_file(root, "spec/#{ctx_prefix}#{snake}/commands/#{Hecks::Utils.underscore(cmd.name)}_spec.rb",
                         spec_gen.generate_command_spec(cmd, agg, context_module: ctx_mod))
            end

            agg.events.each do |evt|
              write_file(root, "spec/#{ctx_prefix}#{snake}/events/#{Hecks::Utils.underscore(evt.name)}_spec.rb",
                         spec_gen.generate_event_spec(evt, agg, context_module: ctx_mod))
            end
          end
        end
      end

      def generate_domain_rb(root)
        dsl = DslSerializer.new(@domain).serialize
        write_file(root, "domain.rb", dsl)
      end

      def inject_autoloads(code, autoloads, agg_name, context_module)
        return code if autoloads.strip.empty?

        marker = "class #{agg_name}\n"
        code.sub(marker, "#{marker}#{autoloads}\n\n")
      end

      def write_file(root, relative_path, content)
        path = File.join(root, relative_path)
        FileUtils.mkdir_p(File.dirname(path))
        File.write(path, content)
      end

    end
    end
  end
end
