require "fileutils"
require_relative "runtime_writer"

module HecksStatic
# Hecks::Generators::Standalone::GemGenerator
#
# Generates a complete, self-contained domain gem that has zero runtime
# dependency on the hecks framework. The generated gem includes its own
# runtime/ directory with the Model, Command, EventBus, QueryBuilder,
# and other framework components inlined and namespaced under the domain
# module. Reuses the existing domain generators with a mixin_prefix
# option to swap Hecks:: references to the domain module.
#
#   gen = GemGenerator.new(domain, output_dir: "./generated")
#   gen.generate  # => path to generated standalone gem
#
class GemGenerator
  def initialize(domain, version: "0.1.0", output_dir: ".")
    @domain = domain
    @version = version
    @output_dir = output_dir
  end

  def generate
    gem_name = @domain.gem_name
    standalone_name = @domain.name.downcase + "_static"
    mod = @domain.module_name + "Domain"
    root = File.join(@output_dir, standalone_name)

    FileUtils.mkdir_p(root)

    # Write inlined runtime
    RuntimeWriter.new(mod).write(root, gem_name)

    # Write domain code (aggregates, commands, events, etc.)
    generate_entry_point(root, gem_name, mod)
    generate_aggregates(root, gem_name, mod)
    generate_queries(root, gem_name, mod)
    generate_ports(root, gem_name, mod)
    generate_adapters(root, gem_name, mod)
    generate_services(root, gem_name, mod)
    generate_middleware(root, gem_name, mod)
    generate_server(root, gem_name, mod)
    generate_bin(root, gem_name, mod)
    generate_gemspec(root, gem_name, mod)
    generate_domain_rb(root)

    root
  end

  private

  def generate_domain_rb(root)
    serializer = Hecks::DslSerializer.new(@domain)
    File.write(File.join(root, "hecks_domain.rb"), serializer.serialize)
  end

  def generate_gemspec(root, gem_name, mod)
    content = <<~RUBY
      Gem::Specification.new do |s|
        s.name        = "#{gem_name}"
        s.version     = "#{@version}"
        s.authors     = ["Generated by Hecks"]
        s.summary     = "#{mod} domain model (standalone)"
        s.files       = Dir["lib/**/*"]
        s.require_paths = ["lib"]
        s.add_dependency "webrick", ">= 1.7"
        s.add_development_dependency "rspec", "~> 3.0"
      end
    RUBY
    File.write(File.join(root, "#{gem_name}.gemspec"), content)

    gemfile = <<~RUBY
      source "https://rubygems.org"
      gem "webrick", ">= 1.7"
    RUBY
    File.write(File.join(root, "Gemfile"), gemfile)
  end

  def generate_entry_point(root, gem_name, mod)
    gen = EntryPointGenerator.new(@domain)
    dir = File.join(root, "lib")
    FileUtils.mkdir_p(dir)

    # Entry point — always regenerated (autoloads + constants)
    File.write(File.join(dir, "#{gem_name}.rb"), gen.generate_entry_point(mod, gem_name))

    # Boot file at project root — only written if it doesn't exist (stable wiring)
    boot_path = File.join(root, "boot.rb")
    File.write(boot_path, gen.generate_boot(mod, gem_name)) unless File.exist?(boot_path)
  end

  def generate_aggregates(root, gem_name, mod)
    @domain.aggregates.each do |agg|
      agg_dir = File.join(root, "lib", gem_name, Hecks::Utils.underscore(agg.name))
      FileUtils.mkdir_p(agg_dir)

      # Aggregate class
      gen = Hecks::Generators::Domain::AggregateGenerator.new(agg, domain_module: mod, mixin_prefix: mod)
      agg_source = gen.generate

      # Inject autoloads for VOs, entities
      autoloads = Hecks::Generators::Infrastructure::AutoloadGenerator.new(@domain)
        .aggregate_autoloads(agg, gem_name)
      agg_source = inject_autoloads(agg_source, agg.name, autoloads)
      File.write(File.join(agg_dir, "#{Hecks::Utils.underscore(agg.name)}.rb"), agg_source)

      generate_value_objects(agg, agg_dir, mod)
      generate_entities(agg, agg_dir, mod)
      generate_commands(agg, agg_dir, mod)
      generate_events(agg, agg_dir, mod)
      generate_policies(agg, agg_dir, mod)
      generate_specifications(agg, agg_dir, mod)
    end
  end

  def generate_value_objects(agg, agg_dir, mod)
    agg.value_objects.each do |vo|
      gen = Hecks::Generators::Domain::ValueObjectGenerator.new(vo, domain_module: mod, aggregate_name: agg.name)
      File.write(File.join(agg_dir, "#{Hecks::Utils.underscore(vo.name)}.rb"), gen.generate)
    end
  end

  def generate_entities(agg, agg_dir, mod)
    agg.entities.each do |ent|
      gen = Hecks::Generators::Domain::EntityGenerator.new(ent, domain_module: mod, aggregate_name: agg.name)
      File.write(File.join(agg_dir, "#{Hecks::Utils.underscore(ent.name)}.rb"), gen.generate)
    end
  end

  def generate_commands(agg, agg_dir, mod)
    cmd_dir = File.join(agg_dir, "commands")
    FileUtils.mkdir_p(cmd_dir)
    agg.commands.each_with_index do |cmd, i|
      event = agg.events[i]
      gen = Hecks::Generators::Domain::CommandGenerator.new(cmd,
        domain_module: mod, aggregate_name: agg.name,
        aggregate: agg, event: event, mixin_prefix: mod)
      File.write(File.join(cmd_dir, "#{Hecks::Utils.underscore(cmd.name)}.rb"), gen.generate)
    end
  end

  def generate_events(agg, agg_dir, mod)
    evt_dir = File.join(agg_dir, "events")
    FileUtils.mkdir_p(evt_dir)
    agg.events.each do |evt|
      gen = Hecks::Generators::Domain::EventGenerator.new(evt, domain_module: mod, aggregate_name: agg.name)
      File.write(File.join(evt_dir, "#{Hecks::Utils.underscore(evt.name)}.rb"), gen.generate)
    end
  end

  def generate_policies(agg, agg_dir, mod)
    return if agg.policies.empty?
    pol_dir = File.join(agg_dir, "policies")
    FileUtils.mkdir_p(pol_dir)
    agg.policies.each do |pol|
      gen = Hecks::Generators::Domain::PolicyGenerator.new(pol, domain_module: mod, aggregate_name: agg.name)
      File.write(File.join(pol_dir, "#{Hecks::Utils.underscore(pol.name)}.rb"), gen.generate)
    end
  end

  def generate_specifications(agg, agg_dir, mod)
    return if agg.specifications.empty?
    spec_dir = File.join(agg_dir, "specifications")
    FileUtils.mkdir_p(spec_dir)
    agg.specifications.each do |spec|
      gen = Hecks::Generators::Domain::SpecificationGenerator.new(spec,
        domain_module: mod, aggregate_name: agg.name, mixin_prefix: mod)
      File.write(File.join(spec_dir, "#{Hecks::Utils.underscore(spec.name)}.rb"), gen.generate)
    end
  end

  def generate_queries(root, gem_name, mod)
    @domain.aggregates.each do |agg|
      next if agg.queries.empty?
      q_dir = File.join(root, "lib", gem_name, Hecks::Utils.underscore(agg.name), "queries")
      FileUtils.mkdir_p(q_dir)
      agg.queries.each do |query|
        gen = Hecks::Generators::Domain::QueryGenerator.new(query,
          domain_module: mod, aggregate_name: agg.name, mixin_prefix: mod)
        File.write(File.join(q_dir, "#{Hecks::Utils.underscore(query.name)}.rb"), gen.generate)
      end
    end
  end

  def generate_ports(root, gem_name, mod)
    port_dir = File.join(root, "lib", gem_name, "ports")
    FileUtils.mkdir_p(port_dir)
    @domain.aggregates.each do |agg|
      gen = Hecks::Generators::Infrastructure::PortGenerator.new(agg, domain_module: mod)
      File.write(File.join(port_dir, "#{Hecks::Utils.underscore(agg.name)}_repository.rb"), gen.generate)
    end
  end

  def generate_adapters(root, gem_name, mod)
    adapter_dir = File.join(root, "lib", gem_name, "adapters")
    FileUtils.mkdir_p(adapter_dir)
    @domain.aggregates.each do |agg|
      gen = Hecks::Generators::Infrastructure::MemoryAdapterGenerator.new(agg,
        domain_module: mod, mixin_prefix: mod)
      File.write(File.join(adapter_dir, "#{Hecks::Utils.underscore(agg.name)}_memory_repository.rb"), gen.generate)
    end

    # Filesystem adapter template
    template_dir = File.expand_path("../templates", __dir__)
    source = File.read(File.join(template_dir, "filesystem_adapter.rb"))
    File.write(File.join(adapter_dir, "filesystem_repository.rb"), source.gsub("__DOMAIN_MODULE__", mod))
  end

  def generate_services(root, gem_name, mod)
    return if @domain.services.empty?
    svc_dir = File.join(root, "lib", gem_name, "services")
    FileUtils.mkdir_p(svc_dir)
    @domain.services.each do |svc|
      gen = Hecks::Generators::Domain::ServiceGenerator.new(svc, domain_module: mod)
      File.write(File.join(svc_dir, "#{Hecks::Utils.underscore(svc.name)}.rb"), gen.generate)
    end
  end

  def generate_bin(root, gem_name, mod)
    bin_dir = File.join(root, "bin")
    FileUtils.mkdir_p(bin_dir)

    # Domain name as CLI command (e.g. "pizzas")
    cmd_name = @domain.name.downcase

    cli_script = <<~'RUBY'.gsub("__GEM__", gem_name).gsub("__MOD__", mod).gsub("__CMD__", cmd_name)
      #!/usr/bin/env ruby
      # Re-exec outside Bundler if we're inside a parent bundle
      if ENV["BUNDLE_GEMFILE"] && !ENV["HECKS_STANDALONE"]
        clean_env = ENV.to_h.reject { |k, _| k.start_with?("BUNDLE") || k == "RUBYOPT" || k == "RUBYLIB" }
        clean_env["HECKS_STANDALONE"] = "1"
        exec(clean_env, RbConfig.ruby, $0, *ARGV)
      end
      $LOAD_PATH.unshift(File.expand_path("../lib", __dir__))
      require "__GEM__"

      command = ARGV.shift

      case command
      when "serve", "ui"
        port = ARGV.find { |a| a =~ /^\d+$/ }&.to_i || 9292
        adapter = ARGV.find { |a| a =~ /^--adapter=/ }&.then { |a| a.split("=").last&.to_sym } || :memory
        __MOD__.reboot(adapter: adapter) if adapter != :memory
        puts "__MOD__ on http://localhost:#{port} (adapter: #{adapter})"
        __MOD__.serve(port: port)
      when "console"
        require "irb"
        puts "__MOD__ console (memory adapter)"
        IRB.start
      when "generate"
        ENV["HECKS_SKIP_BOOT"] = "1"
        project_root = File.expand_path("..", __dir__)
        domain_file = File.join(project_root, "hecks_domain.rb")
        unless File.exist?(domain_file)
          puts "No hecks_domain.rb found in #{project_root}"
          exit 1
        end
        require "hecks"
        domain = eval(File.read(domain_file), nil, domain_file, 1)
        require "hecks_static"
        HecksStatic::GemGenerator.new(domain, output_dir: File.dirname(project_root)).generate
        puts "Regenerated domain from hecks_domain.rb"
      when "info"
        puts "__MOD__"
        puts "  Adapter: #{__MOD__.config[:adapter]}"
        puts "  Events:  #{__MOD__.events.size}"
        __MOD__.domain_info.each do |name, info|
          puts "  #{name}: #{info[:count]} records, #{info[:commands].size} commands"
          info[:ports].each { |role, methods| puts "    #{role}: #{methods.join(', ')}" }
        end
      else
        puts "__CMD__ — __MOD__ standalone domain"
        puts ""
        puts "Commands:"
        puts "  __CMD__ serve [PORT] [--adapter=memory|sqlite]   Start HTTP server with UI"
        puts "  __CMD__ ui [PORT]                                 Alias for serve"
        puts "  __CMD__ console                                   IRB with domain loaded"
        puts "  __CMD__ generate                                  Regenerate domain from hecks_domain.rb"
        puts "  __CMD__ info                                      Show domain config"
      end
    RUBY
    path = File.join(bin_dir, cmd_name)
    File.write(path, cli_script)
    File.chmod(0o755, path)
  end

  def generate_middleware(root, gem_name, mod)
    # Validations extension
    template_dir = File.expand_path("../templates", __dir__)
    source = File.read(File.join(template_dir, "validations.rb"))
    File.write(File.join(root, "lib", gem_name, "validations.rb"), source.gsub("__DOMAIN_MODULE__", mod))
  end

  def generate_server(root, gem_name, mod)
    server_dir = File.join(root, "lib", gem_name, "server")
    FileUtils.mkdir_p(server_dir)

    template_dir = File.expand_path("../templates", __dir__)

    # Copy base server + UI templates
    %w[server ui].each do |name|
      source = File.read(File.join(template_dir, "#{name}.rb"))
      File.write(File.join(server_dir, "#{name}.rb"), source.gsub("__DOMAIN_MODULE__", mod))
    end

    # Generate domain-specific routes (JSON API)
    File.write(File.join(server_dir, "domain_app.rb"), ServerGenerator.new(@domain).generate(mod, gem_name))

    # Generate domain-specific UI routes (HTML)
    File.write(File.join(server_dir, "ui_routes.rb"), UIGenerator.new(@domain).generate(mod, gem_name))
  end

  def inject_autoloads(source, agg_name, autoload_lines)
    return source if autoload_lines.empty?
    lines = source.split("\n")
    # Insert after the class line
    class_idx = lines.index { |l| l =~ /class #{agg_name}/ }
    return source unless class_idx
    lines.insert(class_idx + 1, *autoload_lines.map { |l| "    #{l}" })
    lines.join("\n") + "\n"
  end
end
end
