# Hecks::HTTP::JsonSchemaGenerator
#
# Generates a single JSON Schema document from a domain with all
# aggregates, value objects, commands, and queries as definitions.
#
module Hecks
  module HTTP
    class JsonSchemaGenerator
      def initialize(domain)
        @domain = domain
      end

      def generate
        {
          "$schema" => "https://json-schema.org/draft/2020-12/schema",
          title: "#{@domain.name} Domain Schema",
          description: "Generated by Hecks",
          definitions: build_definitions
        }
      end

      private

      def build_definitions
        defs = {}
        @domain.aggregates.each do |agg|
          defs[agg.name] = aggregate_def(agg)
          agg.value_objects.each { |vo| defs["#{agg.name}::#{vo.name}"] = value_object_def(vo) }
          agg.commands.each { |cmd| defs[cmd.name] = command_def(cmd) }
          agg.events.each { |evt| defs[evt.name] = event_def(evt) }
          agg.queries.each { |q| defs["#{agg.name}.#{Hecks::Utils.underscore(q.name)}"] = query_def(agg, q) }
        end
        defs
      end

      def aggregate_def(agg)
        props = { id: { type: "string", format: "uuid" } }
        required = ["id"]
        agg.attributes.each do |attr|
          if attr.list?
            vo = agg.value_objects.find { |v| v.name == attr.type.to_s }
            props[attr.name] = { type: "array", items: vo ? { "$ref" => "#/definitions/#{agg.name}::#{vo.name}" } : { type: "object" } }
          else
            props[attr.name] = property(attr)
          end
        end
        props[:created_at] = { type: "string", format: "date-time" }
        props[:updated_at] = { type: "string", format: "date-time" }
        { type: "object", properties: props, required: required }
      end

      def value_object_def(vo)
        props = {}
        vo.attributes.each { |attr| props[attr.name] = property(attr) }
        { type: "object", properties: props }
      end

      def command_def(cmd)
        props = {}
        required = []
        cmd.attributes.each do |attr|
          props[attr.name] = property(attr)
          required << attr.name.to_s
        end
        { type: "object", properties: props, required: required }
      end

      def event_def(evt)
        props = { occurred_at: { type: "string", format: "date-time" } }
        evt.attributes.each { |attr| props[attr.name] = property(attr) }
        { type: "object", properties: props }
      end

      def query_def(agg, query)
        params = query.block.parameters
        {
          description: "Returns array of #{agg.name}",
          parameters: params.map { |_, n| { name: n.to_s, type: "string" } },
          returns: { type: "array", items: { "$ref" => "#/definitions/#{agg.name}" } }
        }
      end

      def property(attr)
        if attr.json?
          { type: ["object", "array"] }
        elsif attr.reference?
          { type: "string", format: "uuid", description: "Reference to #{attr.type}" }
        else
          case attr.ruby_type
          when "Integer" then { type: "integer" }
          when "Float" then { type: "number" }
          else { type: "string" }
          end
        end
      end
    end
  end
end
