# Hecks::HTTP::OpenapiGenerator
#
# Generates an OpenAPI 3.0 spec from a domain. Every aggregate gets
# CRUD paths, every query gets a GET path. Types derived from DSL.
#
# Path building  -> OpenapiGenerator::PathBuilder
# Schema building -> OpenapiGenerator::SchemaBuilder
# Response helpers -> OpenapiGenerator::ResponseHelpers
#
require_relative "openapi_generator/response_helpers"
require_relative "openapi_generator/schema_builder"
require_relative "openapi_generator/path_builder"

module Hecks
  module HTTP
    class OpenapiGenerator
      include ResponseHelpers
      include SchemaBuilder
      include PathBuilder

      def initialize(domain)
        @domain = domain
      end

      def generate
        {
          openapi: "3.0.0",
          info: { title: "#{@domain.name} API", version: "1.0.0", description: "Generated by Hecks" },
          paths: build_paths,
          components: { schemas: build_schemas }
        }
      end
    end
  end
end
