# Hecks::HTTP::RpcDiscovery
#
# Generates a JSON-RPC discovery document listing all available methods
# for a domain: commands, queries, and CRUD operations (find, all, count, delete)
# per aggregate. Used by RpcServer to advertise its capabilities.
#
module Hecks
  module HTTP
    class RpcDiscovery
      def initialize(domain)
        @domain = domain
      end

      def generate
        {
          name: "#{@domain.name} RPC",
          description: "Generated by Hecks",
          methods: build_methods
        }
      end

      private

      def build_methods
        methods = []
        @domain.aggregates.each do |agg|
          agg.commands.each do |cmd|
            methods << {
              name: cmd.name,
              description: "#{agg.name} action",
              params: cmd.attributes.map { |a| { name: a.name.to_s, type: a.ruby_type } }
            }
          end
          agg.queries.each do |query|
            qn = Hecks::Utils.underscore(query.name)
            params = query.block.parameters.map { |_, n| { name: n.to_s, type: "string" } }
            methods << { name: "#{agg.name}.#{qn}", description: "#{agg.name} lookup", params: params }
          end
          methods << { name: "#{agg.name}.find", description: "Find #{agg.name} by ID", params: [{ name: "id", type: "string" }] }
          methods << { name: "#{agg.name}.all", description: "List all #{agg.name}s", params: [] }
          methods << { name: "#{agg.name}.count", description: "Count #{agg.name}s", params: [] }
          methods << { name: "#{agg.name}.delete", description: "Delete #{agg.name}", params: [{ name: "id", type: "string" }] }
        end
        methods
      end
    end
  end
end
