# Two SQLite databases because "we need to separate concerns"
# (narrator: they did not separate concerns)

default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  primary:
    <<: *default
    database: db/development.sqlite3
  telegraph:
    <<: *default
    database: db/telegraph.sqlite3
    migrations_paths: db/telegraph_migrate

production:
  primary:
    <<: *default
    database: db/production.sqlite3
  telegraph:
    <<: *default
    database: db/telegraph_production.sqlite3
    # "We'll move this to Postgres eventually" — 2021
