// GENERATED by bin/project_kernel_capabilities from QuerySpecification::Common::COMPARATORS.
// Do not hand-edit — re-run bin/project_kernel_capabilities instead.
//
// Ground truth: Hecksagain::QuerySpecification::Common::COMPARATORS
// (lib/hecksagain/query_specification/common/comparators.rb) — the
// same eight names Vocabulary::QueryComparator (language/bluebook/
// vocabulary.bluebook) declares and spec/vocabulary_conformance_spec
// holds the runtime to; a where-clause's `op:` admits exactly this
// set (`admits: "Vocabulary::QueryComparator"`, Query::Filter).
//
// UNDISPATCHED, ON PURPOSE — read this file's own name before its
// variants. Every OTHER generated capability enum in this crate
// (AttributeShape, OperatorCategory) is matched exhaustively, with no
// wildcard arm, at exactly one real dispatch site in the hand-written
// kernel — that is the whole mechanism this file's siblings exist to
// protect. QueryComparator has NO such site: `rust/src/kernel/cli.rs`
// refuses every query step before any comparator is ever inspected
// ("query steps are not generated yet" — the same "whole_kind" gap
// bin/rust_coverage already documents, one layer up, at the
// construct-kind level; this is that gap's own operator vocabulary,
// named at the LANGUAGE level for the first time). So this enum is
// generated and NOTHING in this crate matches over it — no `_ =>`
// arm to worry about because there is no `match` at all. It exists so
// the eight names below are TRACKED starting now, rather than staying
// undiscoverable until the day a query engine gets built and someone
// has to go re-derive them from Ruby by hand. Add a real dispatch
// site against this enum the day that day comes, and it will already
// refuse to compile non-exhaustively — the ordinary guarantee, just
// starting later than usual.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[allow(dead_code)]
pub enum QueryComparator {
    Eq,
    Ne,
    Gt,
    Gte,
    Lt,
    Lte,
    In,
    Contains,
}

impl QueryComparator {
    pub const ALL: &'static [QueryComparator] = &[QueryComparator::Eq, QueryComparator::Ne, QueryComparator::Gt, QueryComparator::Gte, QueryComparator::Lt, QueryComparator::Lte, QueryComparator::In, QueryComparator::Contains];
}
