require "spec_helper"

RSpec.describe Hecks::HTTP::TypescriptGenerator do
  let(:domain) do
    Hecks.domain "Pizzas" do
      aggregate "Pizza" do
        attribute :name, String
        attribute :price, Float
        attribute :vegetarian, :boolean
        attribute :points, JSON
        attribute :toppings, list_of("Topping")
        attribute :category, String, enum: %w[classic gourmet]

        value_object "Topping" do
          attribute :name, String
          attribute :amount, Integer
        end

        command "CreatePizza" do
          attribute :name, String
          attribute :price, Float
        end

        query "Classics" do
          where(style: "Classic")
        end

        lifecycle :status, default: :draft do
          transition "CreatePizza" => "active"
          transition "ArchivePizza" => "archived"
        end

        command "ArchivePizza"
      end

      aggregate "Order" do
        reference_to "Pizza"
        attribute :quantity, Integer

        command "PlaceOrder" do
          reference_to "Pizza"
          attribute :quantity, Integer
        end
      end
    end
  end

  let(:output) { described_class.new(domain).generate }

  describe "header" do
    it "includes a generated-by comment" do
      expect(output).to start_with("// Generated by Hecks")
      expect(output).to include("Pizzas domain types")
    end
  end

  describe "aggregate interfaces" do
    it "generates an interface for each aggregate" do
      expect(output).to include("export interface Pizza {")
      expect(output).to include("export interface Order {")
    end

    it "includes id, createdAt, updatedAt fields" do
      expect(output).to match(/id: string;/)
      expect(output).to match(/createdAt: string;/)
      expect(output).to match(/updatedAt: string;/)
    end

    it "maps scalar types correctly" do
      expect(output).to match(/name: string;/)
      expect(output).to match(/price: number;/)
      expect(output).to match(/vegetarian: boolean;/)
    end

    it "maps JSON attributes to Record<string, unknown>" do
      expect(output).to match(/points: Record<string, unknown>;/)
    end

    it "maps list attributes as arrays of the child type" do
      expect(output).to match(/toppings: Topping\[\];/)
    end

    it "maps enum attributes as string union types" do
      expect(output).to match(/category: "classic" \| "gourmet";/)
    end

    it "maps references as string fields with comment" do
      expect(output).to match(/pizza: string; \/\/ Reference to Pizza/)
    end
  end

  describe "value object interfaces" do
    it "generates an interface for value objects" do
      expect(output).to include("export interface Topping {")
      expect(output).to match(/name: string;/)
      expect(output).to match(/amount: number;/)
    end
  end

  describe "command types" do
    it "generates a type for each command" do
      expect(output).to include("export type CreatePizza = {")
      expect(output).to include("export type PlaceOrder = {")
    end

    it "includes command attributes with correct types" do
      # PlaceOrder has quantity: Integer and reference_to Pizza
      expect(output).to match(/quantity: number;/)
    end

    it "maps reference params as string with comment" do
      expect(output).to match(/pizza: string; \/\/ Reference to Pizza/)
    end
  end

  describe "event types" do
    it "generates a type for each event" do
      expect(output).to include("export type CreatedPizza = {")
      expect(output).to include("export type PlacedOrder = {")
    end

    it "includes occurredAt field" do
      expect(output).to match(/occurredAt: string;/)
    end
  end

  describe "lifecycle enums" do
    it "generates an enum for lifecycle states" do
      expect(output).to include("export enum PizzaStatus {")
      expect(output).to include('Draft = "draft"')
      expect(output).to include('Active = "active"')
      expect(output).to include('Archived = "archived"')
    end
  end

  describe "output validity" do
    it "produces non-empty output" do
      expect(output.length).to be > 100
    end

    it "does not contain Ruby-isms" do
      expect(output).not_to include("nil")
      expect(output).not_to include("=>")
      expect(output).not_to include("attr_reader")
    end
  end
end
