require "spec_helper"
require "open3"

# R5 (docs/audits/2026-08-11-bug-triage.md) -- the actual build-failure
# half of the finding: `cargo build --features banking` used to fail
# with E0252 ("the name `active` is defined multiple times") because
# rust/Cargo.toml's `default = ["<whichever domain was last
# generated>"]` stays enabled unless `--no-default-features` is also
# passed, so `--features banking` alone enabled BOTH the default
# domain's `active` re-export and banking's, in
# rust/src/generated/mod.rs.
#
# Fixed in rust/src/generated/mod.rs (regenerated by bin/project_rust,
# see its own header comment there): the default domain's own re-export
# now backs off whenever any OTHER domain feature is also enabled, and
# two NON-default domain features enabled together get an explicit,
# named compile_error! instead of the bare E0252.
#
# `io: true` -- real `cargo build` invocations, same convention as
# rust_conformance_spec.rb / hecks_build_pipeline_spec.rb.
RSpec.describe "Rust domain Cargo features are mutually exclusive (R5)", io: true do
  DFE_RUST_DIR = File.join(InMemoryDomain::ROOT, "rust")

  def cargo_build(*args)
    stdout, stderr, status = Open3.capture3("cargo", "build", *args, chdir: DFE_RUST_DIR)
    [status.success?, stdout + stderr]
  end

  it "`cargo build --features banking` succeeds WITHOUT --no-default-features" do
    # This is the exact command the audit recorded as failing to
    # compile. rust/Cargo.toml's `default` feature is whichever domain
    # was most recently generated (today: roster) -- the whole point of
    # the fix is that this succeeds regardless of what `default` is, not
    # just when it happens to already be "banking".
    ok, output = cargo_build("--features", "banking")
    expect(ok).to be(true), "cargo build --features banking failed:\n#{output}"
  end

  it "a bare `cargo build` (whichever domain is currently `default`) still succeeds unaffected" do
    ok, output = cargo_build
    expect(ok).to be(true), "plain cargo build failed:\n#{output}"
  end

  it "`--no-default-features --features banking` (the old required workaround) still works too" do
    ok, output = cargo_build("--no-default-features", "--features", "banking")
    expect(ok).to be(true), "cargo build --no-default-features --features banking failed:\n#{output}"
  end

  # THE GENUINE CONFLICT -- two domains that are BOTH explicitly
  # requested (neither one is just along for the ride via `default`)
  # can't both be the crate's one `generated::active` -- this should
  # still fail, but with our own named compile_error! rather than a bare
  # "defined multiple times".
  it "two explicitly-requested, non-default domain features fail with a clear, named compile_error!" do
    ok, output = cargo_build("--features", "banking,pizzas")
    expect(ok).to be(false), "expected --features banking,pizzas to fail (both are real, non-default domains)"
    expect(output).to include("domain features are mutually exclusive")
    expect(output).to include("banking")
    expect(output).to include("pizzas")
  end
end
