module Hecksagain
  # HOW lib/hecksagain/vocabulary.rb IS RENDERED, kept beside the
  # framework rather than inside bin/ so the spec can regenerate in
  # memory and compare — the same split bin/project_parser_table and
  # spec/parser_table_spec already use.
  #
  # Reads the language's own JUDGED IR, not the raw builder graph: the
  # sets are declared in `vocabulary.bluebook` and reach this having
  # already round-tripped through the meta-domain, so what is written
  # out is what the language actually holds.
  module VocabularyTable
    HEADER = <<~RUBY.freeze
      # GENERATED by bin/project_vocabulary from
      # lib/hecksagain/language/bluebook/vocabulary.bluebook
      #
      # DO NOT EDIT. spec/vocabulary_table_spec.rb regenerates this in memory
      # and refuses a diff, so an edit here fails the ordinary suite.
      #
      # Plain data on purpose — no requires, no dependency on the model —
      # because several of these sets are read while a bluebook is still
      # being parsed. A table that needed the framework to load could not
      # be the table the framework loads with.
    RUBY

    module_function

    # FULL ROWS, not just the first field of each.
    #
    # Most vocabularies ARE one-field lists and the field is the term.
    # Several are not: `Comparison` declares the algebra each operator
    # computes with, `RefusalTemplate` declares an error plus its key and
    # text. Taking the first field of those produced a list of thirty-nine
    # duplicated error names — well-formed and meaningless. So the rows
    # are carried whole, and `fetch` derives the term list from them.
    def tables
      aggregate = Bluebook::MetaValidator.grammar_registry
                                         .bluebook("Bluebook")
                                         .aggregates.find { |a| a.name == "Vocabulary" }

      aggregate.value_objects.to_h do |vo|
        [vo.hecks_name, vo.members.map { |row| row.to_h.transform_keys(&:to_s).transform_values(&:to_s) }]
      end
    end

    def render
      rows = tables.sort_by(&:first).map do |name, members|
        "      #{name.inspect} => [\n" +
          members.map { |row| "        #{row.inspect}.freeze" }.join(",\n") +
          "\n      ].freeze"
      end

      <<~RUBY
        #{HEADER}
        module Hecksagain
          module Vocabulary
            TABLES = {
        #{rows.join(",\n")}
            }.freeze

            # THE TERMS — the first field of each row, which for a
            # one-field vocabulary is the whole of it. Derived ONCE and
            # frozen rather than mapped per call: these are constant
            # tables, and a constant that allocates a new array every
            # time it is read is not one.
            TERMS = TABLES.transform_values { |rows| rows.map { |row| row.values.first }.freeze }.freeze

            module_function

            # Refuses an unknown name rather than answering nil: a set
            # the language does not declare is a typo, not an empty set.
            def fetch(name) = TERMS.fetch(name)

            # The rows whole, for the vocabularies that carry more than a
            # term — Comparison's own algebra, RefusalTemplate's text.
            def rows(name) = TABLES.fetch(name)

            def symbols(name) = fetch(name).map(&:to_sym)

            def names = TABLES.keys
          end
        end
      RUBY
    end
  end
end
